### ISSUE TITLE
VBET Sausage Links - Metrics wishlist brainstorm 

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#108]
## Global Metrics
These are reported for every standard threshold (and user-promoted threshold) - e.g. 50% , *60%*.... 90%, 100%:
### Basic
- Area (hectares, sq km, acres, sk mi.)
- Proportion VB (e.g. for a HUC there is 200 km2 of area, and 5% is valley bottom)
  - Gross
  - By network/riverscape category (e.g. perennial, intermittent,  i.e. NHD FCODE)
  - By Ownership
  - By Ecoregion
- Length of transportation network intersecting valley bottom  (or specific - road, road type, railroad)

### RS Context stuff we have
Not sure if this belongs in RCAT or here because it might not require run-specific parametrization
- Land Use Intensity
- LANDFIRE Veg Class proportions within - producing a categorical bar plot distribution or pie chart

### Geometry
- Total Riverscape Length
- Integrated Riverscape Width
- Bankfull Width (from Input)
- 
- Ratio of Bankfull Width to Valley Bottom Width
- Total Channel Length
- Primary Channel Length
- Valley Bottom Sinuosity = RS Length / Straight-line Riverscape Length

- Sinuosity Flavors (GNAT)?
  - Effective Flow Length
- Riverscape Density (Riverscape Length / Total Watershed Area) 
 

## Interactive Tools
- Playing with probabilistic threshold as first-cut estimate of Active Channel vs. Active Floodplain vs. Inactive Floodplain
- Playing with detrended elevation threshold as first-cut estimate of Stage 0 surfaces, incised surfaces, Inactive surfaces (almost TErX within VB)
- Once symbolized and segregated, give areas (and horizontal bar plots) by above categories - 
  - Proportion Active
  - Proportion Inactive 
  - Proportion Active Channel
  - Proportion Active FP
- For those polygons, calculate average height above or below Stage 0 gradeline
- Maybe more RCAT... but Recovery Potential can be estimated initially and conservatively by:
  - A user-defined LAND USE INTENSITY THRESHOLD 
  - plus the Floodplain Inaccessability... 
The above could be produced as horizontal bar plots for each of the thresholds

## Mask Metrics
Using the concept we've described in GCD of AOI vs. Class Masks, to produce same global metrics, but for particular areas of interest, or of polygons of same type (e.g. USFS vs. BLM vs. Prvate) summaries.

## Local (Sausage Link) Metrics
Is actually all above...

**Comment by joewheaton** [comment]
@MattReimer this is where we laid out the Masking ideas.

@lauren-herbine and @shelbysawyer, please have a read and start asking questions if anything isn't clear here.

**Comment by wally-mac** [comment]
@joewheaton thanks for flushing this out.  @Cashe93 and I have been brainstorming about similar metrics for the on-screen digitizing that we have been doing for the BLM and BoR in Utah so it's great to see that we are coming up with similar and the same metrics.

I understand the Metrics you have come up and think that they will add a ton of value **but I'm not sure what you are asking for.  Is it an attribute table in a shapefile that we populate and pass on to NAR, or what?**  

Please let me know and then we'll work on the task.

**Comment by joewheaton** [comment]
Just a reminder to folks, please provide some critical feedback here. @lauren-herbine and @shelbysawyer I will ask you to provide yours in some vignettes you can link to from here.

**Comment by wally-mac** [comment]
@joewheaton , @lauren-herbine , @shelbysawyer @Cashe93 Here is some feedback on the Global Metrics:

**Geometry** 
- 	In order to have the lengths calculated we will need to run a centerline of the valley bottom and the centerline will house the global metric attributes. 

**Interactive Tools**

_Active/inactive floodplain comparisons_

- As we know, currently our tools do not generate Active Channel, Active Floodplain, and Inactive Floodplain. So, currently this can only be done where these features have been on-screen digitized.
	Note: As of 12/1/20, Karen and Tyler are working on extending RIM to include these comparisons

_Detrended elevation thresholds_

- 	This seems super useful but we need to discuss this more as a team and get all the specifics on how to do this lined out.  

_Recovery potential_
- To make sure we are on the same page, an initial and conservative Recovery potential polygon could be derived from the accessible portion of the valley bottom, which could be further refined by land use intensity values. Is that what you are thinking?
