### ISSUE TITLE
Bankfull Width Buffer

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#12]
Implement bankfull width buffer instead of constant buffer in the current version. Here's the RCAT implementation of the CRB bankfull width:

https://github.com/Riverscapes/RCAT/blob/master/BankfullChannel.py#L281-L303

**Comment by philipbaileynar** [comment]
@KellyMWhitehead a few more resources relating to precipitation...

Back when I was developing the new version of BRAT I needed to use PRISM precipitation data. I developed some [code that extracts PRISM data from the original download file and stores it in a more simple SQLite database](https://github.com/Riverscapes/riverscapes-tools/tree/master/packages/brat/scripts/precipitation). It simply stores the latitude, longitude and mean precipitation. This was a fast hack. There are other PRISM parameters that I ignored that might be useful.

<img width="422" alt="Screen Shot 2020-09-09 at 9 24 03 AM" src="https://user-images.githubusercontent.com/8645379/92626105-555a3e00-f27e-11ea-8892-7d6acb7f667a.png">


I then wrote some [code in BRAT to calculate the mean annual precipitation within a HUC polygon boundary](https://github.com/Riverscapes/riverscapes-tools/blob/master/packages/brat/scripts/hydro_parameters.py#L123-L146). It does a quick extent rectangle SQL select to minimize the processing and then uses Shapely to determine only those PRISM locations explicitly within the boundary polygon.

Hopefully this is helpful for the bankfull width calculation in VBET that uses precipitation.

**Comment by KellyMWhitehead** [comment]
@joewheaton @joewheaton 
Bankfull width buffer calculation is working, however for small streams, the rasterization/polygon process  (blue pixels) is breaking up the valley bottom (green): 
![image](https://user-images.githubusercontent.com/10746997/93380482-1c890e80-f814-11ea-8098-8d1dc6c02ddc.png)

The small stream bf width is calculated at ~3.5m, and the cell size is ~7m. This was not an issue before with the 25m buffers that were much greater than the cell resolution. 

Thoughts on the best path forward?

**Comment by joewheaton** [comment]
Hi @KellyMWhitehead and @philipbaileynar  
I'm not sure if the path forward got captured from our check-in last week somewhere else? I didn't see it so here goes something:

## For Riverscapes Context Projects & VBET
- [ ] Please include/expose (via business logic) three bankfull width algorithm derivatives
  - [ ] Bankfull symbolized channels on drainage network (i.e. polylines with different colors and/or width)
  - [ ] Bankfull polygon (raw) which is nothing more than 0.5 * BFwidth buffer with rectangular caps for each segment so you end up with a _schematic_ representation of relative BFwidth estimate for entire drainage network.
  - [ ] Bankfull polygon merged (union? or replacing segments intersected) into waterbodies NHD polygon

## For VBET
- [ ] Please do not attempt to convert actual polygons for calculation of "channel" line of evidence into a raster that is a fixed resolution or resolution based on size of that channel. Instead, like GCD, always use the concurrent raster as the DEM from which the VBET run is based. For NED, that would be 10 m. This does mean that for small valley bottoms, it will be an over-estimated, single pixel (10 m) trace. That's fine. We *may choose* for these narrow valley bottoms to NOT apply the same probability about water body cells, and instead make them a lower probability because it is just an overestimate based on NHD channel position.  Or we could check for situations where the valley bottom is only 1 pixel wide and flag if the actual estimated bankfull is less than this. This layer should be included as an intermediate, and should be used to help calculate the probability that cell is a valley bottom cell raster (most important output in many ways).
- [ ] Please include/expose (via business logic) for VBET
  - [ ] Same inputs polygons and polyline as used in Riverscape Context
  - [ ] Intermediate (like you do now) that shows the raster approximation of channel cells

**Comment by philipbaileynar** [comment]
@KellyMWhitehead let's revisit this as you're working through VBET.

**Comment by KellyMWhitehead** [comment]
Bankfull now getting generated in RS context: 6a5fa05834dc2dce9a6239b75a0eb788911ff006

**Comment by MattReimer** [comment]
Hey @KellyMWhitehead , Can you just confirm this is working:
https://data.riverscapes.xyz/#/PUBLIC_DATA/65ffaea3-4738-49e7-af98-d10058c38824
then move this ticke to "Done" in the project

**Comment by KellyMWhitehead** [comment]
Looks good.
