### ISSUE TITLE
RVD Comparison Videos

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#209]
Here are two videos by @tyler1218hatch comparing sqlRVD with pyRVD. Please watch and remove yourself from this issue when you have done so. Last person on the ticket should close the issue when they are done.

* [Part 1](https://youtu.be/62HpW9jDu_s)
* [Part 2](https://youtu.be/OULobeKnnhU)

**Comment by philipbaileynar** [comment]
Here's the moment in the video where the first big difference appears. 

https://youtu.be/62HpW9jDu_s?t=498

**Comment by philipbaileynar** [comment]
For completeness, here's Wally describing a problem with the original pyRVD... Might be useful.

https://youtu.be/hDNT1nuKLJY

**Comment by KellyMWhitehead** [comment]
Riparian Vegetation could be due to differences in how each tool uses the landfire classifications.  sqlRVD simply finds all classifications with "Riparian" in the name. I could not find the classification used by pyRVD.

Land Use Intensity is likely getting stored as integer instead of float.

The Thiessen polygons worked for me when I loaded them from RAVE. Perhaps Tyler was using an older version of RAVE?

**Comment by philipbaileynar** [comment]
Very old ticket. RVD has been rewritten and consumed into RCAT.
