### ISSUE TITLE
Grain size

### ISSUE THREAD

**Issue by lauren-herbine** [Riverscapes/riverscapes-tools#237]
What grain size metric do we want for GNAT and Mississippi reach typing?
What units?
Input data sources

**Comment by joewheaton** [comment]
Check out:
https://github.com/Riverscapes/grain-size-tool

**Comment by lauren-herbine** [comment]
## Using [Grain Size Tool](https://github.com/Riverscapes/grain-size-tool)
Inputs:

- [ ] stream network
- [ ] precipitation map
- [ ] DEM
- [ ] regional values for t_c and n
- [ ] [regional equations](https://water.usgs.gov/osw/programs/nss/pubs.html) for Q_2

**Comment by philipbaileynar** [comment]
We have come a long way since Braden wrote this tool. We now have flow accumulation from the NHDPlusHR data and Q2 from the regional curve approach developed by BRAT (although I'm unsure we want to research 1000 regional curve formulas for all Mississippi eight digit HUCs). @lauren-herbine let's chat because I have a database of all the curves that might be more efficient than reading a zillion PDF files.

A quick review of Braden's code suggests that 99% of it is housekeeping and data preparation. The real magic sauce is the handful of equations in this file:

https://github.com/Riverscapes/grain-size-tool/blob/master/GrainSizeReach.py

As @lauren-herbine pointed out we have everything except regional values for `t_c` and `n`.

Questions:

* What variables do `t_c` and `n` represent? I couldn't figure it out among the vast volumes of documentation (wink)
* Where do we get these values?

**Comment by philipbaileynar** [comment]
... and are t_c and n constant for all reaches in all watersheds? If not how do we plan on parameterizing these values?

**Comment by lauren-herbine** [comment]
Unfortunately, definitely not. Would like to chat with @joewheaton about this

**Comment by joewheaton** [comment]
Wow, this is rather circular logic. I must confess I didn't realize this was the case.  You can't do reasonable estimates of critical Shields stress or n without knowing roughly D. I'm guessing that Braden just used constants and ran the thing. I suspect it works roughly okay in smaller, fairly uniform catchments and is really just reflecting differences in local slope and drainage area. The examples Snyder et al (2013) used in Maine are all really gravel bed rivers. Our channel width estimates will be a lot less useful, but we can just use integrated width from our channel area projects. 

![image](https://user-images.githubusercontent.com/9723905/185204531-03a74c1d-4db5-4857-8bc6-64089968c6f2.png)

They point out that their model doesn't do well with D_50_ < 16 mm (i.e. fine grained systems). @lauren-herbine have you played with running this in different local reaches and what constants you use for knowing shields stress and n? You could just take reaches from BRAT hydrology and get a feel if this is going to work.
