### ISSUE TITLE
anthropogenic margins

### ISSUE THREAD

**Issue by lauren-herbine** [Riverscapes/riverscapes-tools#240]
How do we want to measure this for GNAT and Mississippi reach typing?
What units?
Input data sources

**Comment by joewheaton** [comment]
@shelbysawyer, @lauren-herbine, @philipbaileynar and @KellyMWhitehead  should all take a careful look at this. Start by taking a closer look at both the confinement tool and BRAT. In the process of taking this look, we should be writing the documentation (yet to be on https://tools.riverscapes.xyz/) for RSTools/Confinement Tool (we need to decide if this is or is not a [GNAT thing](https://tools.riverscapes.xyz/gnat/)). 

## Clarifications on Confinement 

The confinement tool (and method) defines all valley bottom margins as "potentially" confining, but they are flagged as "active confining margins" when the active channel abuts them.  We have a confinement metric and a constriction proportion metric. 
![image](https://user-images.githubusercontent.com/9723905/109426554-86a10480-79ab-11eb-80e4-b160ca204fae.png)

How its done:
![image](https://user-images.githubusercontent.com/9723905/109426774-8ead7400-79ac-11eb-9ee2-53a4009dc747.png)
-----------
## Incomplete/Inconsistent Literature Definitions

Before calculating something, we should get clarity from the literature that exists on this and make sure what we calculate is consistent and builds off of these concepts.

In Fryris et al. (2015), we talk a little about this and made the mistake of describing "antrhopogenic structures" instead of anthropogenic margins and then also call them "artificial confining features:
![image](https://user-images.githubusercontent.com/9723905/109426310-3e351700-79aa-11eb-88fa-a638c542354c.png)

Examples from Fyrirs et al. (2015):
![image](https://user-images.githubusercontent.com/9723905/109426222-b0f1c280-79a9-11eb-8cae-23a5cba27485.png)

We were clearer in Wheaton et al. (2015) about this:
![image](https://user-images.githubusercontent.com/9723905/109426350-8e13de00-79aa-11eb-8929-c34e2edbb3c1.png) and anthropogenic margins are clearly defined in Tier 2 (I would suggest we need to map anthropogenic margins within the valley bottom (and we already do this in a mix of BRAT and the floodplain connectivity/accessibility part of RCAT.
![image](https://user-images.githubusercontent.com/9723905/109426401-d501d380-79aa-11eb-81b2-57b9a3e83add.png)

### Anthropogenic Confinement Metric
Finally, in O'Brien et al. (2019) we do define a separate Anthropogenic confinement metric which is the length of the active confining anthropogenic margin (on either side) divided by channel length 

![image](https://user-images.githubusercontent.com/9723905/109426535-6bce9000-79ab-11eb-8fb9-1344a26a1044.png)

----------
# Back to Anthropogenic
It is worth noting that mapping Anthropogenic margins and even calculating anthropogenic confinement is useful.

![image](https://user-images.githubusercontent.com/9723905/109426737-6160c600-79ac-11eb-84e7-39ba86ebf6d9.png)


However, what is it we want in terms of (an) anthropogenic metric(s)?

### What we're not doing currently, but might think about

It is also worth noting that we don't currently have a clean method for contextualizing and comparing anthropogenic confinement to natural confinement.  We have lots of confined and partly-confined rivers where the overall confinement value does not change, but the proportion of confinement being on a "shared" anthropogenic margin might be what we're more interested in. It is different when anthropogenic margins are put out in the middle of a valley bottom and the channel abuts them. 

Things we need to map and summarize measures of by valley bottom segment:

- Total Centerline Length of Active Channel(s)
- Total Left VB "active confined length"
- Total Right VB "active confined length"
- Total Left VB length (i.e. potential confining margin length)
- Total Right VB length (i.e. potential confining margin length)
- Total Anthropogenic Margin Length (note this is not just how long roads or levees are; it is how long those margins are on the right or left side of any/all active margins. So you could have the same 1 mile long road through valley bottom with active channels on both sides be calculated as twice the distance)
- Total Right VB "anthropogenically confined length"
- Total Left VB "anthropogenically confined length"
Obviously the above direct measures then allow calculation of a lot of different metrics. We need to not get lost in this, but think carefully about what we want. I maintain that ultimately the mapping will be more useful than anything, but we might minimally want:

- Anthropogenic Confinement 
- Anthropogenic Constriction Proportion
- % Confinement from Anthropogenic (i.e. what proportion of the calculated confinement is from an anthropogenic margin)
- % Constriction Proportion from Anthropogenic (i.e. what proportion of confined on both sides is from anthropogenic margins)
- % Confinement from Anthropogenic (i.e. what proportion of the calculated confinement is from an anthropogenic margin)
- % Constriction Proportion from Anthropogenic (i.e. what proportion of confined on both sides is from anthropogenic margins)
- Constriction Points (these would be crossings, bridges, and natural examples like debris flow fans that create rapids) - a constriction point is different than constriction portion. It generally does not last longitudinally for more than 5x Bankfull width (i.e. rapid downstream decrease in width to "constricted on both sides" followed by rapid increase in width and no longer constricted) - This is a matter of mapping them and basically identifying them as points and reporting count per riverscape segment or density (e.g.  count / mile or kilometer - see #249 ). 
- Anthropogenic Constriction Points (count and density)
- % Constriction Points Anthropogenic (what % of constriction points are anthropogenic) - should be NaN or NA for segments with no constriction points.



###  Multi-threaded Use Cases?
It is also worth noting that we don't really play out or clarify how to calculate confinement for a valley bottom segment versus a channel reach segment. We have only really calculated this on drainage networks and we're not clear on whether active channel margins and calculation of confinement is for each anabranch separately or for all anabranches and considered for outermost (i.e. closest to VB margins).

**Comment by philipbaileynar** [comment]
Legacy thinking. Can re-open if it becomes relevant again.
