### ISSUE TITLE
Zonal Statistics of Raster

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#251]
Develop a tool to summarize raster values by polygon zones. 

Low priority as this is already written as raster_buffer_stats2 for brat. Just a matter of adding any enhancements to support gnat.

Things to consider:
* Buffer option?
* Make sure Windowing/looping/masking over large rasters or large number of polygons is efficient. 
* Additional summary metrics (i.e. cell counts)
*

**Comment by joewheaton** [comment]
This is actually going to become an incredibly high priority soon for interactivity. I really like this. I think we should base this very closely on [Zonal Statistics Tools](https://desktop.arcgis.com/en/arcmap/10.3/tools/spatial-analyst-toolbox/h-how-zonal-statistics-works.htm), but unlike their tools I think we should not separate out, but instead combine the options to do these in one:
- [Zonal Statistics Tool](https://desktop.arcgis.com/en/arcmap/10.3/tools/spatial-analyst-toolbox/zonal-statistics.htm) - which outputs a raster with the resulting statistic for the region(s) in the mask (least useful)
- [Zonal Statistics as Table](https://desktop.arcgis.com/en/arcmap/10.3/tools/spatial-analyst-toolbox/zonal-statistics-as-table.htm) - which outputs a table with a row for each mask or zone and the columns representing the statistics
- [Zonal Statistics Histogram](https://desktop.arcgis.com/en/arcmap/10.3/tools/spatial-analyst-toolbox/zonal-histogram.htm) - Calculates histogram of zone values (note this will require i) a symbology layer file, ii) specification of bins, iii) automatic calculation of bins
![](https://desktop.arcgis.com/en/arcmap/10.3/tools/spatial-analyst-toolbox/GUID-4D22D862-B31A-452C-A2F9-FA880FF35B2E-web.png)
- [Zonal Geometry as Table](https://desktop.arcgis.com/en/arcmap/10.3/tools/spatial-analyst-toolbox/zonal-geometry.htm) - Calculates the specified geometry measure (area, perimeter, thickness, or the characteristics of ellipse) for each zone in a dataset.

In addition, I would like (because we do them all the time)
- Zonal Categorical Horizonal Bar Plot (require a symbology defined and can work on continuous or categorical rasters)
- Zonal Categorical Pie Chart
- 
## Inputs & Outputs
![image](https://user-images.githubusercontent.com/9723905/109397467-f0f66e00-78f3-11eb-8b26-2c3e7e310f4a.png)

Maybe we do something  like:
`ZonalStatistics (in_zone_data, zone_field, in_value_raster, {statistics_type}, {ignore_nodata} , out_table, {out_graph})`

| Parameter                  | Explanation                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | Data Type                     | 
|----------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------|
| in_zone_data               | Dataset that defines the zones. The zones can be defined by an integer raster or a feature layer.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Raster Layer \ Feature Layer | 
| zone_field                 | Field that holds the values that define each zone. It can be an integer or a string field of the zone dataset.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | Field                         | 
| in_value_raster            | Raster that contains the values on which to calculate a statistic.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | Raster Layer                  | 
| statistics_type (Optional) | Statistic type to be calculated. |
| ignore_nodata (Optional)   | Denotes whether NoData values in the Value input will influence the results of the zone that they fall within. | Boolean                       | 


## Statistics to Calculate as Table
> Additional summary metrics (i.e. cell counts)
Yes @KellyMWhitehead! I would also suggest that the table outputs each row for each "zone", but then the last two row in table are for "Total Raster" (regardless if in zones) and for "Total of All Zones". These help contextualize the statistics calculated.

I think we should include both the traditional *statistics* and the additional *attributes* denoted with *italics*:
| **Statistic**          | Zone input type   | Value input type | Output        | 
|--------------------|-------------------|------------------|---------------|
| Majority           | Integer or String | Integer *        | Integer       | 
| Maximum            | Integer or String | Integer, Float   | Same as Value | 
| Mean               | Integer or String | Integer, Float   | Float         |
| Median             | Integer or String | Integer *        | Integer       |
| Minimum            | Integer or String | Integer, Float   | Same as Value |
| Minority           | Integer or String | Integer *        | Integer       |
| Range              | Integer or String | Integer, Float   | Same as Value |
| Standard deviation | Integer or String | Integer, Float   | Float         |
| Sum                | Integer or String | Integer, Float   | Float         |
| Variety            | Integer or String | Integer *        | Integer            |
| *Cell Count* | Integer  or string| Integer, Float        |  Integer |
| *Area* | Integer  or String| Integer, Float      |  Float (projection units^2)|
| *Perimeter* | Integer  or String| Integer, Float      |  Float (projection units) |

Each row above is a column in the output table (by default all should be calculated).

**Comment by philipbaileynar** [comment]
Lots of good material here. A basic zonal statistics tool now exists within QRiS. Here's a link to the documentation page (that as yet has no content ;-)

https://qris.riverscapes.net/software-help/zonal-statistics/
