### ISSUE TITLE
NHD connectors increasing confinement

### ISSUE THREAD

**Issue by lauren-herbine** [Riverscapes/riverscapes-tools#313]
Not sure if this is an already known issue, but thought I'd note here for record keeping. 

Confining polygons (and therefore raw confinement, confinement ratio, and constriction ratio) are not calculating correctly around the NHD connecting flowlines within reservoirs/lakes. Recorded a lil video [here](https://youtu.be/1ANgggBY2e4)

![image](https://user-images.githubusercontent.com/73319684/120862349-0825a700-c546-11eb-95bf-04b3176aeee4.png)

**Comment by lauren-herbine** [comment]
Looks like this is similar to #312

**Comment by joewheaton** [comment]
So @lauren-herbine, @KellyMWhitehead both VBET and confinement right now need some actual thinking on what the inputs should be. Inputs to Confinement are generally wrong... need geomorphology eyes. One thing to be careful with is that confinement is a "channel network" calculation and tool that requires a valley bottom riverscape as an input to calculate it. By contrast, the VBET is actually a riverscape network tool. Many of the problems in confinement right now, are because a) we don't have VBET yet doing what we want, b) we're not using the "right" vbet output, and c) we're not filtering this down to what channel(s) network we want it calculated for.

**Comment by philipbaileynar** [comment]
VBET and confinement have been rewritten since this ticket.
