### ISSUE TITLE
Asotin HAND hillshade

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#318]
Kelly,

Can you include a LiDAR hillshade layer in the Asotin HAND project and re-upload it please?

I don't mind how you generate the hillshade (Arc, Q, GDALDEM etc), so long as its generated from the LiDAR DEM. Just adding it to the existing project and then re-uploading the project should only cause the hillshade and project XML to get uploaded.

https://data.riverscapes.xyz/#/AsotinIMW/cb1bb4ff-fb80-472d-a536-87067a8b3aef

**Comment by KellyMWhitehead** [comment]
Done.

**Comment by joewheaton** [comment]
So I downloaded the [project](https://data.riverscapes.xyz/#/AsotinIMW/cb1bb4ff-fb80-472d-a536-87067a8b3aef) and the hillshade is there. I am more interested though in getting HAND dialed in how we want it and having this work for VBET too.  
- [ ] Can you please verify whether you made changes to HAND tool so that it automatically derives the hilllshade from the DEM? If not, we need a new one.
- [ ] Can you please confirm why this run was run with a polyline and NOT a polygon? I thought Steve provided a polygon that Nadine produced?
![image](https://user-images.githubusercontent.com/9723905/123526448-3ace4580-d695-11eb-811b-f23fb12c1246.png)

**Comment by joewheaton** [comment]
@nick4rivers you may find this interesting.

**Comment by philipbaileynar** [comment]
Jordan has rewritten VBET since this ticket was created. No further action. Closing.
