### ISSUE TITLE
update_brat_parameters failing for some users

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#339]
@tyler1218hatch is trying to run `scripts/update_brat_parameters.py` using the `brat_data_steward`

but he gets:

![unnamed](https://user-images.githubusercontent.com/1063391/125138910-5d645380-e0c4-11eb-97bc-7799c67cbe0e.png)

Seems like maybe a permissions problem?

**Comment by tyler1218hatch** [comment]
@philipbaileynar Any updates on this? If there's a quick workaround for this, let me know. I just need the watershed parameters updated for this one run.

**Comment by philipbaileynar** [comment]
Sorry @tyler1218hatch 

I just set a reminder to do this at 9am. Should be quick.

**Comment by tyler1218hatch** [comment]
Thanks!

**Comment by philipbaileynar** [comment]
@tyler1218hatch I do not get this error. And I have confirmed that `brat_data_steward` can indeed read from the watersheds table.

What credentials do you have in your .env file in your Python environment. DON'T POST THEM HERE. Perhaps give me a ping on Google Chat or BaseCamp to discuss.

**Comment by philipbaileynar** [comment]
I have tweaked my setup so that I am now running update parameters using the `brat_data_steward` postgres account. I get past the error that @tyler1218hatch was having but then it fails for me when it is trying to determine the primary keys of tables by reading from the postgres `information_schema.table_constraints` table:

https://github.com/Riverscapes/riverscapes-tools/blob/master/packages/brat/scripts/update_brat_parameters.py#L74-L80

Running this query on the root account returns rows. Running it as data steward does not. Which then causes an error in the script.

**Comment by philipbaileynar** [comment]
Script was tweaked. No one reported the error in 2 years. Closing.
