### ISSUE TITLE
Understand why TWI producing NoData and -1 outputs, and decide strategy for VBET

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#355]
In #325 we saw some weird outputs for the topographic wetness index that @KellyMWhitehead implemented.  There were a number of places with NoData within the DEM raster grid, and that didn't make sense. There were also areas with -1 as answer, which is also odd. 

> @joewheaton I have a question about TWI related to the updated csv that @KellyMWhitehead provided. I'm noticing a lot of -1 values, which I didn't experience when I queried the layer in Arc / Q. Is the -1 a true TWI output or is there something odd happening somewhere along the way?

Anyhow, we need to get to the bottom of this as this is now an input in VBET and one of the many outputs of TauDEM. As such, maybe we can answer following below (or split into own tickets)

- [ ] 1. Why do areas (many within valley bottom) produce NoData as output? Should we over-ride?
- [ ] 2. Why do some cells produce -1 for TWI? Are these real, or is this an algorithmic bug?
- [x] 3. Assuming we will have some NoData and/or -1 values, how do we handle these in VBET? 
- [x] #356

**Comment by joewheaton** [comment]
@philipbaileynar you may have some insights or thoughts on this (and especially coping strategy 3).

**Comment by joewheaton** [comment]
@shelbysawyer, I still think we should come up with some rough answers to 1 & 2 (tasks above) just for our documentation (#377 ). However, the real side step to this is that when we average lines of evidence, we just don't use it. 

@KellyMWhitehead and @philipbaileynar can you confirm that:

> 3. Assuming we will have some NoData and/or -1 values, how do we handle these in VBET?

The current version of TauDEM simply lets these be NoData or - 1 and VBET does not use them for averaging if this is the case (e.g. only uses slope and HAND).

**Comment by shelbysawyer** [comment]
Circling back to this for documentation purposes.

> * [ ]  1. Why do areas (many within valley bottom) produce NoData as output? Should we over-ride?

This is a result of how TWI is calculated. TWI = ln(a / tan(B)). In theory, flat areas within valley bottoms should be the wettest and quickest to saturate. Therefore, we expect the highest TWI values here. However, if B (the slope gradient) is zero, tan(B) is also zero, giving us a division by zero (infinity). I'm guessing that this infinite quantity gets converted to NoData when the raster is packaged up for VBET. @KellyMWhitehead is that right? 

Technically, it's not an issue with the TWI formula-- these areas should have the highest index value and infinity is.. infinitely high! But, it's not a value, meaning that somewhere along the way, the values in those cells are tossed and NoData is subbed in their place. 

Where does this leave us for VBET? If we only care about TWI because of its role as a line of evidence.. then I don't see an issue as long as VBET isn't using them to reach the averaged likelihood value. I feel like this is okay, considering that these areas are either 1) considered 0.99 likelihood already because they are included in the Channel Area Polygon input or 2) going to be very high likelihood for slope and HAND. Either way, it will be important to include our reasoning in the documentation for both TauDEM and VBET. 

> * [ ]  2. Why do some cells produce -1 for TWI? Are these real, or is this an algorithmic bug?

I looked through some recent projects (ex. [VBET-07020005](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/b9c503a0-6eb5-43ee-8098-619bad68933a
)) and do not see -1 values. Looks like this problem has been handled somewhere else along the way.

Closing this for now, but can reopen if more discussion is needed.

**Comment by MattReimer** [comment]
Ok @shelbysawyer thanks for looking into this!

I don't think it's a problem here but be careful when you're looking for strange values when using our RAVE symbolizations. Last week I spent an hour trying to figure out why I wasn't seeing it and then realized our RAVE symbolizations exclude anything outside their ranges so things like wacky values or corrupt nodata values can become invisible on first glance. 

Important safety tip FYI: @joewheaton @philipbaileynar @KellyMWhitehead @jtgilbert

**Comment by shelbysawyer** [comment]
Yes @MattReimer! I noticed that.. RAVE symbology hides some of those problems. As I work through the projects in #637, I'll keep that in mind.

Going back to [this](https://github.com/Riverscapes/riverscapes-tools/issues/355#issuecomment-1332702506) comment, I think the TWI layer has the potential to be misleading(?) when we're looking for anomalies. For example, when I first started checking out TWI, I saw this and all of the holes with no data jumped out as red flags:

<img width="875" alt="twi" src="https://user-images.githubusercontent.com/73311751/205108553-840a8862-5d98-45a8-8b82-5b8204a389cd.PNG">

The next red flag was when the Channel Area Polygons input layer didn't "explain" all of those zero slope (so TWI no data) areas:
<img width="889" alt="twichannel" src="https://user-images.githubusercontent.com/73311751/205108997-89730ab1-4cd6-4fc6-90c8-5e295ad65045.PNG">

But.. flicking on some aerial imagery shows that TWI is right. This landscape is just very, very wet-- kettle lake country!
<img width="887" alt="twiandimagery" src="https://user-images.githubusercontent.com/73311751/205109310-3a68c66d-55c5-4a1f-84db-cfdb2feea06f.PNG">

And although Channel Area Polygons capture quite a few of these water bodies, it also misses a fair amount:
<img width="891" alt="twichannelimage" src="https://user-images.githubusercontent.com/73311751/205109461-7a1a3085-6a99-4cf4-9fc9-14150e393b3c.PNG">

Anyway.. what I think these quick pictures help illustrate is that, so far, TWI seems to be working the way we expect and the no data values are also falling where we expect to see them. I will be combing through the projects in #637 and keeping an eye out for exceptions. @joewheaton Please let me know if this thought process / approach sounds good.

**Comment by MattReimer** [comment]
Yeah, this is a great way to see it. 

We might want to look into baking bright pink values into all our color ramps for symbologies so that anomalous values stick out like a sore though.... just a thought.
