### ISSUE TITLE
[Windows] .env file loading and `safe_makedirs` method doesn't work on windows

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#43]
We need to normalize how windows paths are stored in `.env` files, how they're read by the `settings.py` file and then how they work inside `safe_makedirs`

Whatever changes you make should make sure that linux paths are also accepted `/soemthing/somethingelse/blah/blah/blah`

The first problem is in the way we load our `.env files`:

https://github.com/Riverscapes/riverscapes-tools/blob/master/lib/commons/rscommons/dotenv.py#L51-L64

There may be other problems hiding behind this first one but we won't know until we fix this.

**Comment by KellyMWhitehead** [comment]
Fixed two lines of code that conflicted with windows file path formats (when loading the paths from .env and when generating a URL for downloading HAND rasters).

I propose to always use the path format of the user's os in the .env file, and handling appropriately. 

1) [pathlib](https://docs.python.org/3/library/pathlib.html) might be helpful for sorting this out. ([example](https://medium.com/@ageitgey/python-3-quick-tip-the-easy-way-to-deal-with-file-paths-on-windows-mac-and-linux-11a072b58d5f))

2) Be careful not to use os.path.join to form URL's, since windows will use backslashes.
