### ISSUE TITLE
Can we add the Watershed name as a metadata tag in all projects downstream projects of RS_Context?

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#439]
I've noticed most of our new projects no longer have the HUC Name (the most obvious thing to most people) as a tag.

**Comment by MattReimer** [comment]
In general we never used the HUC as a tag. 

Here's the staging server (because that's what's coming)

<img width="875" alt="Screen Shot 2021-09-21 at 4 14 23 PM" src="https://user-images.githubusercontent.com/1063391/134259942-c6cbe226-d151-4327-880e-49612d0e78d8.png">

Do you mean we should include the HUC name in project titles?

**Comment by joewheaton** [comment]
Sorry, I should have been clearer @MattReimer  (though thanks for updates on staging server because those are big improvements). Let me show you what I mean:
https://youtu.be/6XxKSauWPDY
[![Video https://youtu.be/6XxKSauWPDY](http://img.youtube.com/vi/6XxKSauWPDY/0.jpg)](http://www.youtube.com/watch?v=6XxKSauWPDY "")

What I should have asked for is if we can bring the `Watershed` label/tag across on all these standard runs. We produce it in `RS_Context` but don't carry it into any of the downstream projects. This would allow adding into the display and sort fields as well as search by tag.

**Comment by MattReimer** [comment]
I think it's already happening. Take a look at some metadata I pulled from a channel area project

```xml
<Vector guid="f8700ed4-3428-493e-921d-5efd09d5f558" id="FLOWLINES">
  <Name>NHD Flowlines</Name>
  <Path>flowlines</Path>
  <MetaData>
    <Meta name="_rs_wh_id">417c447c-c341-415b-85f2-48d0bde758c6</Meta>
    <Meta name="_rs_wh_user">d6c0ff26-8550-4f80-b9ea-6cc1e70a1c4d</Meta>
    <Meta name="_rs_wh_program">Anabranch</Meta>
    <Meta name="_rs_wh_tags">TEST,SEP10</Meta>
    <Meta name="_rs_prj_ModelVersion">1.2.0</Meta>
    <Meta name="_rs_prj_dateCreated" type="isodate">2021-09-14T16:22:17.346097</Meta>
    <Meta name="_rs_prj_HUC8">08080102</Meta>
    <Meta name="_rs_prj_HUC">08080102</Meta>
    <Meta name="_rs_prj_Runner">Cybercastor</Meta>

    <!-- HERE IT IS -->
    <Meta name="_rs_prj_Watershed">Bayou Teche</Meta>

    <Meta name="_rs_prj_mean_annual_precipitation_mm" type="float">1548.931616226658</Meta>
    <Meta name="_rs_prj_ProcTimeS" type="int">2603.27</Meta>
    <Meta name="_rs_prj_ProcTimeHuman">43:23 minutes</Meta>
    <Meta name="_rs_lyr_origin_url" type="url">https://prd-tnm.s3.amazonaws.com/StagedProducts/Hydrography/NHDPlusHR/Beta/GDB/NHDPLUS_H_0808_HU4_GDB.zip</Meta>
    <Meta name="_rs_prj_projType">RSContext</Meta>
    <Meta name="_rs_lyr_id">NHDFlowline</Meta>
    <Meta name="_rs_lyr_guid" type="guid">72c911e8-92fc-4182-8c71-9caf1e553f50</Meta>
    <Meta name="_rs_lyr_path" type="filepath">hydrology/NHDFlowline.shp</Meta>
  </MetaData>
</Vector>
```

Also I know it's carrying through because when I open up WebRAVE it's in the metadata there too:
<img width="240" alt="Screen Shot 2021-09-21 at 4 56 22 PM" src="https://user-images.githubusercontent.com/1063391/134262729-06061f0a-a1dc-4e73-b09c-77d641693da3.png">

Unless I'm still not understanding... which is possible

**Comment by joewheaton** [comment]
Oh, that's awesome. All the better. Than some follow ups:
1. Is this a case of this is happening on new projects in past week or so and I am just not seeing it ones on disk? or Are these only revealed in Staging Warehouse and not live warehouse?
2. Is it a matter of just exposing these at same level up high so they show up in the "primary" project metadata and are searchable/quearable?
![image](https://user-images.githubusercontent.com/9723905/134263888-9304677d-f126-404a-9055-e2d7846b571e.png)

BTW I search for `Bayou Teche` in all my Programs and never find that:
![image](https://user-images.githubusercontent.com/9723905/134264169-38129f36-b295-42b6-914e-0a156c35b229.png)

Is it possible that these don't work because you are showing them burried in a feature's metadata and not as project metadata?

**Comment by MattReimer** [comment]
I think this is happening because only layer metadata flows downward right now. If we want project-level metadata to flow down the chain we need to think carefully about this because layer metadata usually only derives from one parent layer whereas proeject metadata may have two or more parents (i.e. BRAT takes RSContext, ChannelArea, VBET etc)

How we merge this metadata is going to take a bit of a think.

**Comment by joewheaton** [comment]
@MattReimer thanks for info. This is sort of funny. The layer level metadata is far less common and useful than the project level metadata that layer was associated with. Anyhow, happy to set aside for moment and talk about. I will point out that your instantly thinking about how to automate these hand-offs. I appreciate that. I am literally just asking for @KellyMWhitehead and @philipbaileynar to manually enter the tags I want in to the runs they are queueing up at my request ;).  So we can get some short-term wins here without a big complicated solution.

**Comment by MattReimer** [comment]
I think maybe I didn't answer your question or maybe there's still some confusion... which I get because it's got some nuance and semantics to it.

Take a look at this NHD flowline layer from a ChannelArea project:

```xml
<Vector guid="016af337-498a-4eda-bbb7-02a52146a44e" id="FLOWLINES">
  <Name>NHD Flowlines</Name>
  <Path>flowlines</Path>
  <MetaData>
    <Meta name="_rs_wh_id">96affd82-a24a-4214-a246-8f9617514fff</Meta>
    <Meta name="_rs_wh_user">d6c0ff26-8550-4f80-b9ea-6cc1e70a1c4d</Meta>
    <Meta name="_rs_wh_program">Anabranch</Meta>
    <Meta name="_rs_wh_tags">TEST,SEP10</Meta>
    <Meta name="_rs_prj_ModelVersion">1.2.0</Meta>
    <Meta name="_rs_prj_dateCreated" type="isodate">2021-09-14T16:22:21.761164</Meta>
    <Meta name="_rs_prj_HUC8">08010100</Meta>
    <Meta name="_rs_prj_HUC">08010100</Meta>
    <Meta name="_rs_prj_Runner">Cybercastor</Meta>
    <Meta name="_rs_prj_Watershed">Lower Mississippi-Memphis</Meta>
    <Meta name="_rs_prj_mean_annual_precipitation_mm" type="float">1282.4545343734765</Meta>
    <Meta name="_rs_prj_ProcTimeS" type="int">2730.94</Meta>
    <Meta name="_rs_prj_ProcTimeHuman">45:30 minutes</Meta>
    <Meta name="_rs_lyr_origin_url" type="url">https://prd-tnm.s3.amazonaws.com/StagedProducts/Hydrography/NHDPlusHR/Beta/GDB/NHDPLUS_H_0801_HU4_GDB.zip</Meta>
    <Meta name="_rs_prj_projType">RSContext</Meta>
    <Meta name="_rs_lyr_id">NHDFlowline</Meta>
    <Meta name="_rs_lyr_guid" type="guid">9cdc72dc-d515-4489-9328-f4ed431d8026</Meta>
    <Meta name="_rs_lyr_path" type="filepath">hydrology/NHDFlowline.shp</Meta>
  </MetaData>
</Vector>
```

The layer metadata contains the project AND the warehouse AND the layer metadata of the project it came from. This has been standard behaviour for a while and helps tell the story of where that layer came from. Anything marked "_rs_prj_" is the parent's project metadata and anything marked `_rs_wh` is the parent's warehouse metadata (program, warehouse guid etc) and anything marked `_rs_lyr` is from the parent's layer metadata. 

At present the warehouse UI doesn't read any layer information so there's no way to see this (webRAVE does it though. see example above). 

I think we already have all the information we need here to tell the story, we just need the warehouse to read it.

**Comment by joewheaton** [comment]
That's super-helpful. I think you are right @MattReimer, you do have the information buried in the NHD layer in that `_RS_PRJ_Watershed` metadata. So I think we (I) want something like the following for our RS_Context projects:
1. Check to see if `NHD Flowlines` layer exists, and if it does grab the `_RS_PRJ_Watershed` and set a Project Metadata tag of something like '<Meta name="Watershed">' to this value. 
2. Expose in either Mandatory Metadata place in the list and make searchable when searching for projects.

**Comment by MattReimer** [comment]
The workflow for this has been updated for the new warehouse and I think this issue is stale. Let's close it and re-evaluate if it's not correct.
