### ISSUE TITLE
Remove BRAT Waterbodies from high capacity predictions and definition query

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#469]
In the [video](https://youtu.be/drAqjcCcMws) below I explain both the veg parameterization problem of open water (listed as 4, should maybe be 1) and the bigger issue of Artificial Paths not being differentiated between waterbodies and flow areas. 

[![Video Link](http://img.youtube.com/vi/drAqjcCcMws/0.jpg)](http://www.youtube.com/watch?v=drAqjcCcMws "")

@wally-mac and @Cashe93 will be interested in this.

**Comment by wally-mac** [comment]
@joewheaton I like your idea of using the FCODE approach to differentiate artificial paths in waterbodies.  As a reminder in PyBRAT starting with the Utah run we had developed the following approach to differentiate artificial paths in large waterbodies and keep artificial paths in small waterbodies which could actually be beaver dams:
NHD networks flow virtually through lakes, ponds and reservoirs with connecting linework 
known as ‘artificial paths’. In the statewide model we included artificial paths **outside** of large 
water bodies (e.g. lakes and reservoirs) because virtual reconnaissance in Google Earth 
revealed that beaver do not generally build dams on such large water bodies. By contrast, 
artificial paths through small water bodies they do use and in some cases NHD actually picks up 
natural beaver ponds as ‘artificial paths’. For example, we identified a discontinuous streamline 
in the Temple Fork drainage attributed as an artificial path with the centerline running through 
a beaver dam. Using the NHD water body data we established a water body 
threshold size of 500 square meters (a conceivably large beaver pond) at which any stream 
segment running through a water body larger than this threshold was removed from the 
analysis. Using manual editing in Google Earth all stream segments in ponds not considered to 
be beaver ponds were also removed (e.g. the thousands of stock ponds and small reservoirs 
throughout the state). Thus, the only artificial paths that remained were those associated with 
beaver ponds.

As far a the veg coding change from 4 to 1 for 'open water' I'm still "mulling it over" and trying to remember what our justification for a 4 was in the first place.  Please give me some time to look into this a bit more.

**Comment by wally-mac** [comment]
@joewheaton I dug into old email chains and the Utah BRAT report how we have scored Open Water in BRAT in the past and found the following: 

In BRAT we score vegetation for its suitability as a dam building material. So, by that logic, 0 for Open Water makes some sense. However, LANDFIRE classifies some riparian corridors as open water which tends to include both active stream channels as well as areas immediately adjacent which including riparian, wetlands and beaver dam complexes. In the Utah run when these pixels were classified as a 0 it resulted in an underestimate of capacity (this was based on field validation). Therefore, for the Utah run we reclassified open water pixels to more accurately represent the riparian/wetland vegetation that likely exists in these locations. In the north, open water was classified as a 3 and in the south, open water was classified as a 2. The logic being that the majority of the southern regions have a riparian corridor that is dominated by invasive riparian (preference value 2) and that in the north it is likely that what is categorized as open water is actually native riparian/wetland vegetation (with an average preference value 3). 

I could not find an email or a Github ticket that justified why we decided to code Open Water as a 4 but my instincts tell me if we drop it down to a 1 we will underestimate capacity in beaver dam complexes dominated by pixels coded as open water that include inundated wetland/riparian vegetation and beaver dams. 

Based on prior experience I think Open Water should be scored as either a 3 or 4. Not as a 0, 1 or 2.

**Comment by philipbaileynar** [comment]
FYI sqlBRAT supports @wally-mac comment regarding spatially variable suitability. Should you wish you can provide a "vegetation suitability override" for open water on a HUC by HUC basis. This would replicate the north/south approach that USU took in Utah.

**Comment by wally-mac** [comment]
@joewheaton and @philipbaileynar another idea regarding how to improve the way we "score" the Open Water category would be to use the NHD polygons that delineate large rivers as an "analysis mask" where within the polygon the open water class would be scored as a 0 or 1 whereas outside of large river polygon the open water class would be scored as a 3 or 4.
