### ISSUE TITLE
2. Develop a method for improving VBET performance in areas of low slope

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/riverscapes-tools#478]
Right now, VBET is overpredicting in areas of low slope. One idea to address this issue is to change the weighting of normalized evidence (TWI, HAND, and Slope) for areas under a given slope threshold.

- [ ] Slope Task 1 - Look at Slope Analyses using the thresholds we are proposing using.
Currently, the slope symbology is pretty broad on the classes 0-5, 5-10, 10-20, 20-30, 30:
![image](https://user-images.githubusercontent.com/9723905/142676086-078da60c-b38a-4c91-b2a0-332de4eb2957.png)

Since you want to understand how this is going to behave you should use what you're proposing. In other words, if you 

- Slope Task 2 - Look at this in a flat plains watershed that might have

**Comment by joewheaton** [comment]
@KellyMWhitehead and @philipbaileynar can you confirm that this is where in the VBET code you combine evidence:
https://github.com/Riverscapes/riverscapes-tools/blob/fc62981f6e4a0b8432c37ca9ce76f94caa4e2a23/packages/vbet/vbet/vbet.py#L257-L279

I guess it is really here where the combination happens?
https://github.com/Riverscapes/riverscapes-tools/blob/fc62981f6e4a0b8432c37ca9ce76f94caa4e2a23/packages/vbet/vbet/vbet.py#L265

I'm thinking what we want is to:
1. Calculate from distribution of values in the raw slope degrees (`slope`) raster 
2. Calculate proportion of distribution that is below _12_ degrees threshold (TBD) and store as something like 'lowSlopeProportion` .
3. Add a parameter `lowSlopeThreshold` to run with a default (for now) of 0.6 (i.e. 60%) 'lowSlopeProportion` that triggers a different weighting where instead of equally averaged amongst three lines of evidence the slope evidence is weighted at 0.1 and the other two are at 0.45 and 0.45 respectively. 

Something like:

``` python
if lowSlopeProportion > lowSlopeThreshold
   fvals_topo = np.ma.mean([normalized['Slope'], normalized['HAND'], normalized['TWI']], axis=0)
else
  fvals_topo = (([0.1*normalized['Slope'] + 0.45*normalized['HAND'] + 0.45*normalized['TWI']])/3, axis=0)
```

I'm sure I screwed up syntax and there may be better ways to do that, but you get idea...

**Comment by MattReimer** [comment]
Not sure where we're at with this. @shelbysawyer can you review some of the projects here:

https://github.com/Riverscapes/riverscapes-tools/discussions/637

and either close this issue or let us know what's left to do?

**Comment by joewheaton** [comment]
> Not sure where we're at with this. @shelbysawyer can you review some of the projects here:
> 
> #637
> 
> and either close this issue or let us know what's left to do?

The new methods behind VBET (using 3 lines of evidence) more than solve this. Closing.
