### ISSUE TITLE
Science Base URL Error

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#511]
Science base has the wrong URLS so we're getting missions data in our patchwork DEMs that we build for RSContext

Sometimes this fails in Cybercastor and sometimes it just produces blank data

<img width="988" alt="Screen Shot 2021-12-03 at 11 33 40 AM" src="https://user-images.githubusercontent.com/1063391/144662727-0a6fd072-f0ba-4126-bae6-124891a77ee4.png">

1. [x] Implement a fix where we use a lookup table after scraping the S3 bucket.
2. [x] Make sure we fail if the DEM Raster coverage is less than X% (I'd say 85% but use whatever value you think makes sense).
    - [x] Make sure this still works with our HUCs that cross the Canadian border.

**Comment by KellyMWhitehead** [comment]
Summary/context:
1) DEM's are stored in s3 folders that are indexed spatially by lat/long.
2) USGS periodically updates the dems and **adds** them to the folder. They appear in the S3 buckets with the date appended in the filename. Several versions of the dem can appear in the folder.
3) When we spatial query Science base for the intersecting huc dems,  we are getting **every** DEM, which includes the all versions for a particular lat/long. Fortunately GDAL doesn't fuss about this and mosaics them together in the vrt file.
4) However, occasionally science base has returned non-existent data /bad urls.

5) a separate issue of missing data (referenced in the image) was related to producing a processing extent that allowed us to generate riverscapes projects for Canadian-bounding hucs. This is fixed in 6adf397b74df0115032a3bfe10aea4738139a9dd

Fixes:
- Lookup table for cleaning bad urls (#4) implemented in 5b2f6f5f91379aa80aaba9fbaed3de9fc8fb6245
- Added a check to make sure dem data covers at least 85% of the huc boundary. This may cause some Canadian-Bounding hucs to fail, but we can keep an eye out for these.

**Comment by joewheaton** [comment]
Thanks @KellyMWhitehead this is helpful. Can you confirm whether or not fixes have been made in the impacted Mississippi HUCs so that we have the DEMs now, or do you still need @lauren-herbine and I to flag those for you?
