### ISSUE TITLE
Think about whether you want different categories to better align with what VBET is doing and if so work with  to edit form.

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#524]
Original issues convoluted degree of confidence and boundaries.
![image](https://user-images.githubusercontent.com/9723905/146036250-8cb1199a-2039-4e6a-b93e-190af811c5c4.png)
In #477 parent @joewheaton suggested:

>   - For me this is being clearer about what the NHD and NED data think are likelihoods within a pixel and NOT focusing as much on the boundaries between classes (I think previously we muddled these too things)
>        - `Active Channel Area` (where its mapped by NHD, not what it shows on aerial photo)
>        - `Active Floodplain` (pick in middle of 10 m pixels that are at least 1 to 2 pixels wide appear low-enough to flood regularly and are supporting riparian vegetation
>        - `Inactive Floodplain` (areas in middle of 10 m pixels and meet definition of could plausibly flood, but are distinctive from neighboring hillslopes, terraces.
>        - `Terrace` clear examples of terraces that are obviously terraces and clearly from a historic, relic flow-regime (i.e. can't be confused with anthropogenic incision episodes). If not sure, 
>        - `Probably not Valley Bottom` - areas of uncertainty that will help inform the curve's inflection point and be used in validation, likely to be in the largest riverscapes
>        - `Definitely not Valley Bottom` - way up on a mountain top or hillslope

**Comment by joewheaton** [comment]
@lauren-herbine and I on big rivers could use the FEMA maps to differentiate between `Inactive Floodplain`, `Terrace`, and `Probably Not Valley Bottom` categories. 

![image](https://user-images.githubusercontent.com/9723905/146040853-abebb477-230e-4764-b312-6b848a0b271a.png)

Specifically we can take things where we may be tempted to put it in `Terrace` or `Probably not` and definitely map it as `Inactive Floodplain` if it is 0.2% Annual Chance or 1%. By Contrast, floodways, can certainly be mapped as active channel or active floodplain. We need to remember that these are mapped off of higher resolution topography and hydraulic models. 

We could independently use in some areas FEMA maps as a spot validation exercise with the polygons.

**Comment by shelbysawyer** [comment]
@shelbysawyer Just a reminder for myself here on our conversation:
- FEMA mapping is definitely in the VB.. so it's good for checking to see if we're underpredicting
- We also need another line of evidence to inform the other "bound"
- 1:24k soil map quad will be good for informing the other "bound"  - to see how much overpredicting

**Comment by shelbysawyer** [comment]
@joewheaton Should I work with @philipbaileynar to edit the form? I agree with these new categories and definitions:

`Active Channel Area` (where its mapped by NHD, not what it shows on aerial photo)
`Active Floodplain` (middle of 10 m pixels that are at least 1 to 2 pixels wide appear low-enough to flood regularly and are supporting riparian vegetation
`Inactive Floodplain` (middle of 10 m pixels and meet definition of could plausibly flood, but are distinctive from neighboring hillslopes, terraces.
`Terrace` (clear examples of terraces that are obviously terraces and clearly from a historic, relic flow-regime (i.e. can't be confused with anthropogenic incision episodes).
`Probably not Valley Bottom` (areas of uncertainty that will help inform the curve's inflection point and be used in validation, likely to be in the largest riverscapes)
`Definitely not Valley Bottom` - way up on a mountain top or hillslope

Things that I'm still thinking about:
- How these new categories will translate to likelihood values for the creation of transform curves
- How to fit these new categories with our existing observation points (Will they be housed in the same database? If not, how will we redefine existing data to be in agreement with these new categories? If they will be in the same database, let's add a field so that we can indicate that they were collected with different mindsets informing observation decisions)

**Comment by joewheaton** [comment]
> @joewheaton Should I work with @philipbaileynar to edit the form? 

Yes @philipbaileynar can you 

> I agree with these new categories and definitions:
> 
> `Active Channel Area` (where its mapped by NHD, not what it shows on aerial photo) 
> `Active Floodplain` (middle of 10 m pixels that are at least 1 to 2 pixels wide appear low-enough to flood regularly and are supporting riparian vegetation 
> `Inactive Floodplain` (middle of 10 m pixels and meet definition of could plausibly flood, but are distinctive from neighboring hillslopes, terraces. 
> `Terrace` (clear examples of terraces that are clearly from a historic, relic flow-regime (i.e. can't be confused with anthropogenic incision episodes).
>  `Probably not Valley Bottom` (areas of uncertainty that will help inform the curve's inflection point and be used in validation, likely to be in the largest riverscapes)
>  `Definitely not Valley Bottom` (way up on a mountain top or hillslope)
> 
> Things that I'm still thinking about:
> 
> * How these new categories will translate to likelihood values for the creation of transform curves

Well you can go back to the transform functions and we can see exactly what we want them to do...  We also have some old threads you can dig up with @KellyMWhitehead where we forced some of the "approximate geomorphic units"

Recall that >=  0.995 is `active channel`,  0.995 > `active floodplain` >= 0.9 (currently), and 0.9 > `inactive floodplain` >= 0.68.

After that, we don't really differentiate as systematically the others (i.e. anything < 0.68 could be `Probably not Valley Bottom`, `Definitely not Valley Bottom` or `Terrace`. However, terraces would presumably be closer to 0.68 then definitely not valley bottom.

> * How to fit these new categories with our existing observation points (Will they be housed in the same database? If not, how will we redefine existing data to be in agreement with these new categories? If they will be in the same database, let's add a field so that we can indicate that they were collected with different mindsets informing observation decisions)

Let me check in with @philipbaileynar on this. I'm not sure. I suspect it will be in the same.

**Comment by joewheaton** [comment]
These have been updated by @philipbaileynar thanks. Step 1 - Edit all existing (e.g. move, delete and assign appropriate new category). Step 2 - Notify @philipbaileynar when all the old categories are no longer used and he will delete them, and Step 3 - Collect new points.
