### ISSUE TITLE
Get Alden's Plots for HTML report into a dev BRAT branch and make some changes and additions 

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#545]
In #544 there a bunch of new features for the BRAT reports. @jtgilbert I want you to learn from @philipbaileynar how to make edits to the python code (largely using MatplotLib) to start curating and improving the HTML reports across all our [Production-Grade, Network-Scale Tools](https://tools.riverscapes.xyz/).  We will start here with BRAT.

One of the things I tasked @Jdgilby with in our conversation with Brian is start getting the specification for what we want HTML reports to be and include what you want in them. For example this is a uncurated riverscapes context report: https://d3k0pn8xvrx1sy.cloudfront.net/NRCS_CEAP/RSContext/9e9d7020-76b6-4056-877c-ca439706db6d/rs_context.html/index.html.

We're going to start with BRAT. All the graphs will be based on [MatplotLib](https://matplotlib.org/stable/gallery/index). Put another way, if you know what data is there, think about what you want displayed as any of [these examples](https://matplotlib.org/stable/gallery/index)

Also, think back to [reports](https://tools.riverscapes.xyz/brat/references.html) we wrote, and custom figures we produced with lots of horizontal bar plots using the colors from the symbology... that's what we'll base this on. Once we get going, I'll have you work with @CHafen a bit to turn these into what we want.

**Comment by joewheaton** [comment]
FYI @nick4rivers, this will come into play for HTML reports shortly in QRiS

**Comment by philipbaileynar** [comment]
@jtgilbert here is our existing [riverscapes plotting code](https://github.com/Riverscapes/riverscapes-tools/blob/9bfe728cfeddaac815b0aaa30d1b432d51842560/lib/commons/rscommons/plotting.py). Because we tend to reuse the same plot types again and again, we have abstracted them to this single place in the code.

You can reuse whatever charts you need or add more to this centralized code for charting.

It's pretty self explanatory, but shout if you want a walkthrough.

**Comment by philipbaileynar** [comment]
Also here's [my video](https://youtu.be/LV0W8ZBKZiA) from 25 Sep 2021 where I experimented with some of Alden's ideas.
