### ISSUE TITLE
Duplicate reaches in BRAT projects 

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/riverscapes-tools#582]
@Jdgilby noticed that reaches that are coded as artificial paths within river polygons seem to be copied into BRAT projects twice, resulting in exact copies. @philipbaileynar this obviously affects metric calculations because you're double counting all of these segments.

**Comment by philipbaileynar** [comment]
1. Do you have link to a warehouse project that exhibits this problem? I just downloaded a BRAT run (I'm unsure of its provenance) and can't seem to see the problem.
2. Which feature class contains the duplicates? inputs.gpkg or brat.gpkg?

If the problem is in the `vwReaches` perhaps the problem is in a join?

**Comment by jtgilbert** [comment]
Josh initially spotted it here:
https://data.riverscapes.xyz/#/BRAT_CRB/223a86ce-d123-4f88-970e-9faeee6ee1bb

I saw it replicated here:
https://data.riverscapes.xyz/#/BEAR/c01e2bd1-d077-4161-99c2-bdb4727c4d53

It is in `ReachGeometry` in the outputs.gpkg and gets copied into the `vwReaches`

**Comment by jtgilbert** [comment]
This appears to have been resolved in v4.4.0, it was v4.3.x projects that we noticed the problem in.
