### ISSUE TITLE
Project Referencing 4 - Fix all legacy warehouse projects

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#595]
### Project Referencing 4 - Fix all existing CyberCastor runs in warehouse to include these correctly (I'd prefer this is not just a re-run brute force  (i.e. 3) but whatever works).

I'm pretty sure that @MattReimer has this covered for all the CyberCastor runs, and despite the stated preference in title, it probably will just be a re-run. That is fine. We will know when project referencing is working correctly.

**Comment by MattReimer** [comment]
We've actually come up with a migration strategy for old warehouse projects but the migration does not include projects referencing each other because in the old warehouse we've lost that information in a way that's not easy to recreate.

There are some nuances about project dataset sharing I'm not sure anyone but me really gets so I think maybe we need a meeting beetween @philipbaileynar, @joewheaton and myself before I kick off any migration to make sure we all understand the scope and limitations of what's being upgraded.

I won't start it until I'm sure we're all on the same page.

**Comment by joewheaton** [comment]
Sounds good @MattReimer to discuss. Let us know when it rises towards top.

**Comment by MattReimer** [comment]
I believe this work is done. Closing
