### ISSUE TITLE
Synthesized VBET Likelihood raster

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#613]
VBET now operates on a single level path at a time. This means that we have hundreds of individual HAND rasters instead of one for the entire project extent. We can't keep hundreds of individual rasters (because of file size and housekeeping) but it is vital that we can visualize the HAND that drives VBET. 

The goal of this ticket is to develop a single HAND raster for the entire project extent that synthesizes all the individual HAND rasters for each level path. Here's my proposed workflow:

1. Instantiate a new, empty raster that has the dimensions of the entire project (typically HUC8).

2. Loop over each level path in ASCENDING oder of size writing just the values of the thresholded valley bottom to the output raster. This process will overwrite any existing values in the raster. (Given the small-to-large processing order this will result in mainstems trumping smaller tributaries. Note that there will be NODATA gaps outside of the thresholded valley bottoms.)

3. Loop over each level path in DESCENDING order of size. Identify all the stream catchment polygons associated with each level path and write the HAND values to the output raster ONLY WHERE THE OUTPUT RASTER IS NODATA. This will "fill in the gaps" with non-valley bottom HAND values assuming that the most relevant value for each pixel is the drainage in which it occurs. The descending order means that any "shared custody" regions will get assigned to bigger channels. And because every cell must fall in a stream catchment, this should result in all pixels in the dataset getting a HAND values (assuming that all stream catchments are associated with a level path that gets processed).

Finally, I think a few gaps are tolerable... these might be associated with locations that VBET ignores. I don't really know what this means. But I don't want perfection to get in the way of progress. A decent synthesized HAND raster that covers 90% of the HUC would satisfy 99.9% of the need.

**Comment by shelbysawyer** [comment]
Can't wait to check this out. It will be great to have access to this layer and get a better handle on how HAND is driving VBET at the project level, particularly at tributary junctions.

**Comment by KellyMWhitehead** [comment]
Let me write out my thoughts here:

I think we are already doing 1 (raster initialized as the size of the dem) and 2 (writing values to raster that are inside the vbet polygon for that level path, moving from small level paths (longer streams) to large level paths (smallest tributaries).  

For 3, we would move in reverse, from small streams to the largest (largest to smallest wouldn't make sense, as the largest would essentially contain the entire huc watershed). This should be doable, however I currently delete the temp folder on each level path iteration. If I just retain the level path HAND rasters, we should be ok with cybercastor storage constraints.

Finally, I will apply this method for both the existing HAND and Vbet Likelihood composite rasters. This shouldn't change values we are already producing within the vbet areas, just adding data to no-data areas.

**Comment by joewheaton** [comment]
Thanks @philipbaileynar for laying this out...  Thanks @KellyMWhitehead for laying out your thoughts.  This will be the first of a handful of comments and clarifications. 

Starting with the **goal**:
>The goal of this ticket is to develop a single HAND raster for the entire project extent that synthesizes all the individual HAND rasters for each level path. Here's my proposed workflow

After reading what @philipbaileynar spelt out and what @KellyMWhitehead wrote out, it strikes me that what @philipbaileynar proposes WILL work for a synthesized "HAND" raster. This HAND raster would be very useful by itself in units of height above the nearest drainage cell (i.e. m or ft).  However, the title here is a "Synthesized VBET Likelihood Raster". I think that is what @KellyMWhitehead  thinks we're doing. I want ALL three things (yes there is a third) that we used to have, that follow @philipbaileynar proposed workflow of where to write what from memory to (his order of operations is critical).  

The reasons I want all three are for untangling the outputs of VBET. So that is:
- [ ] Synthesized HAND Raster
- [ ] Synthesized HAND Likelihood Raster (i.e. with the variable application of the transform functions between HAND and a likelihood based on HAND)
- [ ] Synthesized VBET Likelihood Raster

Is this possible?

**Comment by joewheaton** [comment]
Oops... I see now that @KellyMWhitehead was saying and assuming same as me:
> Finally, I will apply this method for both the existing HAND and Vbet Likelihood composite rasters. This shouldn't change values we are already producing within the vbet areas, just adding data to no-data areas.

**Comment by joewheaton** [comment]
I really like @philipbaileynar cartoon and explanation. Of course this work outside the valley bottom is less critical, but will essentially be done by drainage wings associated with the level path. I presume we are able to do that @KellyMWhitehead?

**Comment by philipbaileynar** [comment]
Yes @KellyMWhitehead came up with a similar but better way of doing the area outside the valley bottom.

**Comment by joewheaton** [comment]
Awesome @KellyMWhitehead I look forward to learning what you came up with and seeing how it looks. This is the 🗝️ to unlocking interpreting and verifying results. Excited

**Comment by MattReimer** [comment]
This work is done and implemented related to #614 

Closing.
