### ISSUE TITLE
VBET 0.8.2 & 0.83 - BUG in Centerline on Main Levelpath of Bear River Mainstem

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#670]
I am loving the improvements in 0.8.2 and 0.8.3. One thing that showed up (I have not noticed it anywhere else) is the centerline (and therefore the DGOs and IGOs) not making it all the way up the longest levelpath (70000400011364) in the [HUC 1601020204](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/7b37cdb0-098c-4097-a3ca-66ba31a99ca9).

@philipbaileynar and I discussed. Here is the HUC 10 and in red is the levelpath up the mainstem:
![image](https://user-images.githubusercontent.com/9723905/206552593-a5b1595e-1bca-45a6-9f4b-4cf9c28cac22.png)

The problem is the centerline stops about halfway through the levelpath:
![image](https://user-images.githubusercontent.com/9723905/206553074-b9955d73-440e-491e-99a3-7774c2bd12fe.png)

At first I thought it was maybe something to do with Mink Creek, but we are not so sure. 

Associated DGOs and IGOs:
![image](https://user-images.githubusercontent.com/9723905/206553257-61a6cd01-5c6c-4920-a5dc-eed7f135f1c0.png)

**Comment by philipbaileynar** [comment]
thoughts @KellyMWhitehead ?

Joe showed me the cost surface. Looks good. It does go through a VERY  narrow constriction, but it otherwise looks good.

**Comment by KellyMWhitehead** [comment]
I have a theory: we were using a huc8 boundary to clip/mask features to the dem extent during processing. This is especially important for the main level paths, which may start/stop just outside the dem. This was an oversight when we were focused on only running huc8's.

Solution: I realize we have an agnostic "processing_extent" layer in the hydrology.gpkg that we should be using instead of huc8 boundary. Testing underway...

**Comment by KellyMWhitehead** [comment]
This is fixed and ready for upcoming version.

**Comment by KellyMWhitehead** [comment]
[Fixed](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/70bd63fc-b68c-4d8f-9772-66215f0cb5ba) in 8.4.0
