### ISSUE TITLE
Change DGO & IGO spacing to 100m

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#679]
Switch DGO and IGO spacing to 100m. Previously it was 50m.

**Comment by philipbaileynar** [comment]
@joewheaton do you realize that any and all metric analysis windows can only be multiples of IGO spacing?

Are you OK changing any GNAT metrics that involve multiples of 50m to be the nearest 100m analysis window size?

**Comment by joewheaton** [comment]
> @joewheaton do you realize that any and all metric analysis windows can only be multiples of IGO spacing?

Yes.

> 
> Are you OK changing any GNAT metrics that involve multiples of 50m to be the nearest 100m analysis window size?

Yes, I  think 200 m (100 m) is as small a window as we can go meaningfully. I had a really interesting discussion tonight with Simoni about this... We're good.

**Comment by KellyMWhitehead** [comment]
@joewheaton 
our medium stream size window is currently set to 250m. Should we bump this up to 300?

**Comment by joewheaton** [comment]
> @joewheaton 
> our medium stream size window is currently set to 250m. Should we bump this up to 300?


Let's have medium go to 500 m for now. There is some basis for this.... I won't bore you now...

**Comment by KellyMWhitehead** [comment]
Change made for 0.8.5

- IGO spacing at 100m, starting 50m from centerline start.
- IGO metric windows: 200m, 500m, 1000m

**Comment by joewheaton** [comment]
@KellyMWhitehead so I am confused. I didn't think this through. I know I asked for 500 m, but now that I think about it, I don't know how you did this? I thought I could only ask in multiple of DGOs (i.e. 100 m here), so how are you able to do this? Are you going 200 up and 300 down or 300 up and 200 down? I don't see how you can do 250 m up and down with DGOs as they are? If you are doing calculation no-symmetrically, lets change to 600 m window. Otherwise, I need to understand how you are doing this.

@shelbysawyer and @lauren-herbine  FYI.

As far as the 100 m DGO spacing goes, It still seems reasonable even in the first order tributaries.

**Comment by lauren-herbine** [comment]
Thanks for tagging me on this! @joewheaton we started to discuss analysis window sizes a bit ago but never really got around to making any decisions... I'd be curious to know what your discussion with Simoni brought to light. I'd like to see what you think about bumping up the largest analysis window above 1000m. In some of my investigations it seems like that could be useful. Alternatively, GNAT metrics could still be larger than 1 K, correct?

**Comment by joewheaton** [comment]
I am all for bumping up the metric windows to scales that make sense. I'm not convinced that what we are using yet is meaningful. You can do a sensitivity analysis with DGOs for any metric (in multiples of 100 m DGOs).

**Comment by joewheaton** [comment]
You can take any of the DGO attribute tables and assemble VBET metrics for example at different windows sizes and produce plots like this from Gary's paper:
![image](https://user-images.githubusercontent.com/9723905/207916782-183c7ad0-474c-4fc9-99c6-fef9bc599ae9.png)

Of course you can map the differences to:
![image](https://user-images.githubusercontent.com/9723905/207916939-b81fca91-97ee-4e80-af29-5aec773e36de.png)

**Comment by KellyMWhitehead** [comment]
@joewheaton 
After some sleuthing, I think we are both wrong, based on how vbet is currently set up.

Method:
1) igo's are laid out along the centerline based on a specified distance (now at 100m). The first igo is located at 1/2 of this distance (e.g 50m) so that when the dgo's are created, the first one still gets the full spacing. The effect is each igo is located in the center (along the centerline) of the dgo. This is the segment_distance attribute.

2) When we apply a moving window, we select all igos that are 1/2 the window distance upstream and 1/2 the window distance downstream. As an example, for a 200m window with100m igo spacing, the window for igo250 would include the dgos with igo150 through igo350. This is three dgos so the window is actually 300m.

![image](https://user-images.githubusercontent.com/10746997/207957471-a4468b0f-abdf-4f32-af80-7608d864d9aa.png)

So, based on our current setup, the window sizes can be any multiple of n where `window_size = igo_spacing + 2 * n * igo_spacing`

It is important to note that the metrics are calculated based on the clipped centerline distances and dgo areas, so these calculated metrics remain valid. It is only the nominal window sizes that are currently overselecting dgos based on our previous assumptions.

**Comment by joewheaton** [comment]
This is a super helpful explanation @KellyMWhitehead. Many thanks.

**Comment by lauren-herbine** [comment]
Thank you for laying this out @KellyMWhitehead . I just want to make sure I am understanding things:

So for a 200 m analysis window with 100 m spacing, are metrices then calculated on the 3 DGOs- 300 m? OR is the centerline then clipped to 200 m? If so, how are we calculating the metrics? Where are we storing those (new?) intermediates?

For example, a gradient calculation. 

![image](https://user-images.githubusercontent.com/73319684/207994762-553d836a-5da6-422e-b4dc-cc2622f9737e.png)

**Comment by shelbysawyer** [comment]
Thanks @KellyMWhitehead this visual and description really helps me understand how IGOs and DGOs are actually "manufactured" and allow us to pull metrics.

> It is only the nominal window sizes that are currently overselecting dgos based on our previous assumptions.
Sorry, I think I'm still confused about this part. Could you explain this another way?

**Comment by KellyMWhitehead** [comment]
@lauren-herbine 

The top scenario in your diagram is how vbet/gnat operate.
