### ISSUE TITLE
Places where main level path VB is too large, creating tribs that should have IGOs/DGOs but dont.

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/riverscapes-tools#688]
It looks like this is an issue where the mainstem valley bottom generated first, is "traveling up" tribs, so that what should be THEIR valley bottom is bein considered the mainstem valley bottom, and they are not getting DGOs/IGOs. When calculating attributes for IGOs therefore, the riverscape of the trib is being used on the mainstem, and the trib is not getting the summary attributes it should. In the photo here the mainstem Bear is the large VB on the left and is inundating the VB of Trout Creek coming in from the right. This may just be an issue of improved calibration of transform functions to try and avoid overestimating mainstem VBs....

![MidBearVB](https://user-images.githubusercontent.com/21687931/208496660-c080c2e1-5000-49c7-8747-fe658931474f.png)

**Comment by philipbaileynar** [comment]
[Version 0.8.3](https://github.com/Riverscapes/riverscapes-tools/blob/VBET_GNAT/packages/vbet/changelog.md) fundamentally changed how we transform evidence. We now choose a single stream size bin for a level path and then transform all three lines of evidence (slope, TWI and HAND) using the respective transform curves for the selected stream size bin.

This change improved the coherence of VBET, to say nothing about also making it easier to teach and explain. Unfortunately it made worse the one feature that we hoped it would solve.... "tributary protrusions" where the valley bottom for downstream reaches protrudes too far up into tributaries.

We agreed to accept the new approach because the perceived benefits outweigh making the tributary protrusions worse. We will pursue a separate solution to this problem.

**Comment by jtgilbert** [comment]
Ah I see... what was the motivation for a single stream size per level path? I can see it simplifying things but also causing different problems... And what is the criteria for being binned into a given stream size?

**Comment by philipbaileynar** [comment]
Previously we picked and applied stream size bins based on drainage wing catchments.

Picture the most downstream reach of a small tributary where it meets a much bigger river. The drainage wing for the small trib was getting one set of transform curves (those of a small river) whereas the surrounding areas that drain directly into the bigger river were getting different transform curves (those of a big river).

We hypothesized that this was causing two problems:

- sharp transitions in VBET evidence at the boundaries of the small river drainage catchment wing.
- Evidence in the small river drainage catchment wing would favour steeper streams with higher HAND values. We thought this was the cause of the original tributary protrusions.

Turns out we are idiots and know nothing...

We are on the hunt for a new line of evidence that can tease out the tributary protrusions and suppress their VBET evidence for the downstream maintsems. We do not think that the protrusions exhibit any clear signal in our current stack of evidence layers.

ps We recognize that very long level paths might pass through multiple stream size bin sizes. We thought about identifying these "zones" and applying different transform curves to each zone. However, this was going to be time-consuming and complex to code. After a brief review @joewheaton concluded that this doesn't affect too many level paths and so we opted to skip it for now.

**Comment by jtgilbert** [comment]
Got it, based on conversations with some of the tools users, I think that it's going to be really important for documentation to have all of these sorts of choices laid out and justifications explained where applicable. One example, I've had several people ask about, and express concern about the thresholds used to categorize non-vb vs vb, and active vs inactive without out validation gathered to constrain those threshold values.

**Comment by shelbysawyer** [comment]
@jtgilbert That's really useful information Jordan! I will dig into documentation efforts on the VBET front when things are in a more stable place.
