### ISSUE TITLE
VBET: Skewed Centerlines, Odd DGO Geometry

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/riverscapes-tools#698]
[Project link](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/8e568096-aad6-4a2d-b102-ee61e0ecfb63), v. 0.8.6

I've been combing through the latest 0.8.6 VBET runs, and creating some graphics to document the problems I see. This graphic highlights some that I came across in 16010202, Middle Bear.

![16010202_updated](https://user-images.githubusercontent.com/73311751/216704634-4559855d-8427-43e0-b6ec-7c4543bb41c7.png)

- [ ] #700

I don't understand how the centerline is being generated here. To me, the edges of the VB are the outermost ones (illustrated in red in the sketch I made to go with Problem A) and the shapes in the middle are islands of upland, which are excluded from the VB. However, it looks like the centerline is being drawn between the eastern VB edge and the islands, rather than between the two VB edges. It looks like this is resulting in confusion for how the DGOs are drawn, as those appear to reach the western VB edge. As a result, the DGOs have some wild shapes that make it very visually confusing and are unlikely to yield useful metrics.

- [x] #701

The Cub River is missing a centerline. This is a known issue that's been documented a few times (ex. #696, #691, #697).

- [ ] #702

There are areas with missing data, although this is likely a result of LOE raster problems. Is there anything we can do here, or is that just something we need to roll with?

**Comment by joewheaton** [comment]
Thank you for this @shelbysawyer. These are really important. @philipbaileynar and @KellyMWhitehead have been focused on QRiS and other development since prior to Christmas when 0.8.6 was run and there are a bunch of issues like this we need to resolve. There is a confusing intersection of issues, some of which are actual bugs, some of which make sense, given how algoirthm works and are driven by inadequacies of the data and/or our approach (i.e. we live with them) and c) some might improve or go away with some of the calibration (i.e. changing of transform curves and/or changing of evidence weights).  I am gong to be coordinating to get @jtgilbert to help us with understanding these issues and get @KellyMWhitehead and @philipbaileynar back into this as well. 

For now...  lets explode these into their own issues.

**Comment by joewheaton** [comment]
This is dramatically improved now with 0.9. I am closing.
