### ISSUE TITLE
Anthro 0.0.1 - Add the missing layer specific `<MetaData>` in the `project.rs.xml`

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#704]
These projects need some metadata!

**Comment by jtgilbert** [comment]
The layers that are missing metadata are missing it because it will get pulled from upstream projects. The same script that adds the project bounds does this, but like I said in the other issue, I can't run it because of the vbet v1 xml. anything run into the new warehouse will automatically take care of this.

**Comment by philipbaileynar** [comment]
Closing because Jordan's response is correct. Layer metadata will get included when it's run with upstream projects that have metadata.
