### ISSUE TITLE
Duplicating IGOs

### ISSUE THREAD

**Issue by lauren-herbine** [Riverscapes/riverscapes-tools#708]
I discovered this issue while working with 05020004 (Cheat).
According to @KellyMWhitehead , it's been dealt with before, but I am logging it here for record of it popping up again.

In Glade Run (levelpath 24000500009376), IGOs are being duplicated:
![image](https://user-images.githubusercontent.com/73319684/218501177-138fd807-ff7c-48c3-be2f-dbcb3e50d1f6.png)
The segment distance listed twice as 50 show up as these IGOs:
![image](https://user-images.githubusercontent.com/73319684/218501300-ac050ee6-86de-4528-a61f-4444ddeb2483.png)

So we know that they're not just weird geometries that got cutoff from each other.

Centerline segments not re-joining properly so segmentation starts over again?

**Comment by KellyMWhitehead** [comment]
This issue is caused by the centerline getting clipped by the edge of the vbet polygon, thereby restarting the segmentation/sequencing:
![image](https://user-images.githubusercontent.com/10746997/218883435-87697e3c-9e0e-4e2c-a694-074c681f88a2.png)

What is also interesting is the green section of centerline (to the left) is a separate feature. There are no igo's in that section due to smaller than the window size.

I need to review the sequence of clipping to fully understand the cause.

**Comment by lauren-herbine** [comment]
Great, thanks for looking into this @KellyMWhitehead !

**Comment by jtgilbert** [comment]
@joewheaton I'm not sure what exactly was causing it before but it hasn't showed up in the last few versions...
