### ISSUE TITLE
Swamp/Marsh areas and how they will affect Sample Frames

### ISSUE THREAD

**Issue by lauren-herbine** [Riverscapes/riverscapes-tools#712]
This is an issue for @lauren-herbine and @shelbysawyer to come back to once the fix that @jtgilbert lays out in #711 fixes the missing IGO/DGO issue (#696). I am using sample frames to include DGOs, IGOs, centerlines

In areas where there are vast oft-inundated areas that the NHD is labeling as swamps/marshes (46600), we are unsure as to how centerlines and the rest of the sample frames will be created. 
![image](https://user-images.githubusercontent.com/73319684/219787046-606b84cb-148b-4b97-b1f6-37eb889b190f.png)

- Will the flow areas and swamp/marsh areas be combined in the likelihood raster as 1 polygon and therefore there will be only one set of sample frames created for the whole area? or will they remain separate and therefore create multiple sets of sample frames?
![image](https://user-images.githubusercontent.com/73319684/219788653-0427fda9-f0ec-437d-b365-71cd96a7d018.png)

- Are the likelihood rasters accurate? In the Cheat, it looks like HAND is being run off of the flowareas (the mainstems of the rivers and not the extent of the Channel Area polygon, which includes the swamp/marsh area), but in the Flambeau, it looks like HAND is being runoff the Channel Area polygon which is set by the Lake/Pond designation (see second pic below).
![image](https://user-images.githubusercontent.com/73319684/219797326-ec512109-2310-4a48-9d66-75f9f9dd2f15.png)
![image](https://user-images.githubusercontent.com/73319684/219797932-bded7f15-93c9-447d-8353-d0760333bd75.png)
Why are they mapping differently when the Cheat (see 1st figure in this post) also has a large Channel Area polygon? Does it have something to do with the flowarea polygon within the waterbody polygon?

- How do these things behave in other areas where there are swamps/marsh (46600) designations? Do we think this is accurate? I think we need to investigate this on the upper midwest, some parts of the appalachians, and potentially in flatter plains areas? Right now we don't have too many of those projects available

I'm going to update this as I further investigate

**Comment by shelbysawyer** [comment]
Thanks for getting this written out with a bunch of helpful graphics @lauren-herbine. We could potentially convert this to a discussion and break it up into some specific issues as we go. I think I might have additional thoughts to add to part of what you're asking here.

> * Will the flow areas and swamp/marsh areas be combined in the likelihood raster as 1 polygon and therefore there will be only one set of sample frames created for the whole area? or will they remain separate and therefore create multiple sets of sample frames?
>   ![image](https://user-images.githubusercontent.com/73319684/219788653-0427fda9-f0ec-437d-b365-71cd96a7d018.png)

1. From my understanding, once the topographic evidence raster has been created (right now, that's the mean of normalized slope, HAND, TWI raster values), channel area polygons effectively "baked" into the likelihood raster so that in the likelihood raster, all areas that overlap with channel areas have a likelihood value of 0.995. I've seen some evidence of this not actually working, though. @KellyMWhitehead Am I understanding this right?

2. For the area that you're showing in these graphics, the Blackwater River is the longest levelpath. We would expect to see the Blackwater River VB have the most ownership of this area, and then all of the tribs coming into this swamp/marsh will also own some VB area, but much less. That is what we see, despite some overprediction: 
<img width="564" alt="blackwater" src="https://user-images.githubusercontent.com/73311751/219802152-dd18abee-9366-413b-9057-b5cb6a4a4f4a.PNG">

If I'm understanding correctly, you're wondering what will happen for areas that may fall outside of the Blackwater River VB but are still going to get 0.095 likelihood because they're water bodies (in this case, swamp/marsh waterbody)? And how those areas will generate DGOs if they're not obviously connected to a trib?

3. The valley bottom extent polygon is currently generated by thresholding the likelihood raster at 0.68. The centerline is generated from the valley bottom extent. The shapes of the channel area polygons don't play a role here beyond influencing the likelihood raster, and therefore don't affect how the DGOs are drawn.. or shouldn't. That being said-- because we can't currently see the centerline due to the bugs you've already noted, it's hard to say exactly how it will draw. I hope something like your "1 polygon" drawing above.

**Comment by lauren-herbine** [comment]
@shelbysawyer That's a great idea converting to discussion, as I think there may be many issues coming out of this.
And yes

> If I'm understanding correctly, you're wondering what will happen for areas that may fall outside of the Blackwater River VB but are still going to get 0.095 likelihood because they're water bodies (in this case, swamp/marsh waterbody)? And how those areas will generate DGOs if they're not obviously connected to a trib?

This is what I was trying to say!

**Comment by joewheaton** [comment]
@lauren-herbine have you been able to see how this is different yet in 0.9.0? I'm thinking this can likely be closed?

**Comment by lauren-herbine** [comment]
I haven't been able to check yet, I'll keep it open for now until I can see it in marsh areas!

**Comment by shelbysawyer** [comment]
@lauren-herbine Should we close this and reopen if the problem pops up again in new versions?

**Comment by lauren-herbine** [comment]
yes that's a good idea. closing now.
