### ISSUE TITLE
VBET 0.9.0 Review: Parent Issue

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/riverscapes-tools#724]
With the feedback on issues documented in the [VBET 0.8.9 Review: Parent Issue](https://github.com/Riverscapes/riverscapes-tools/issues/719), @jtgilbert will be making the relevant changes and then running a new batch of VBET 0.9.0 projects for us to review.

- @jtgilbert Can you please fill out the "**0.9.0. Fix:**" bullets and also bullet out any other updates / fixes?
- @joewheaton If they will be implemented in this version, can you please add info here on the changes to point spacing that you proposed in our 3/20 meeting?

When reviewing, please make sure to update resources so that you're working with the most current business logic and symbology.

### **VBET 0.9.0 Key Updates & Fixes:**
------

1. **0.8.9 Problem: Holes/islands within large valley bottoms.** As documented in #721, holes are ocurring in valley bottoms. These areas (holes) are then run for other levelpaths. When the evidence rasters are reassembled, the "hole" areas, which belong to smaller levelpaths, end up integrated into the project composite evidence rasters and the likelihood raster. This is a problem because it causes visual confusion (ex. one levelpath's HAND raster being run inside another levelpath's VB / HAND raster), skews the centerline, and disrupts DGOs.
**0.9.0 Fix:** @shelbysawyer @lauren-herbine Here's that Cheat HUC10 with larger hole filling and variable IGO spacing for a first look:
https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/305474b4-9667-4dc5-a4e5-072dfff6bcb0

2. **0.8.9 Problem: TBD**
**0.9.0 Fix:** TBD

3. **0.8.9 Problem: TBD**
**0.9.0 Fix:** TBD

4. **0.8.9 Problem: TBD**
**0.9.0 Fix:** TBD
------
Adding a checklist here to make sure we get eyes on all 20 test HUCs, which will be on the [staging server](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch):

- [ ] 0502000405
- [ ] 1706030402
- [ ] 1019001003
- [ ] 0501000301
- [ ] 0601020704
- [ ] 1601020101
- [ ] 1003020102
- [ ] 1601020303
- [ ] 1019000507
- [ ] 0514020112
- [ ] 0601020203
- [ ] 0702000504
- [ ] 1601020201
- [ ] 1019000309
- [ ] 1601020204
- [ ] 1005001505
- [ ] 1019000209
- [ ] 0504000306
- [ ] 0705000202
- [ ] 1019000402

**Comment by jtgilbert** [comment]
@shelbysawyer @lauren-herbine Here's that Cheat HUC10 with larger hole filling and variable IGO spacing for a first look:
https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/305474b4-9667-4dc5-a4e5-072dfff6bcb0

**Comment by lauren-herbine** [comment]
Overall, looking good! Still an odd thing going on with the valley bottoms in this place:
![image](https://user-images.githubusercontent.com/73319684/226503219-9551f682-2255-4a3c-a5e4-f1b8da8bff64.png)
I couldn't find any islands- could you @shelbysawyer ? If I am correct, looks like the hole filling worked!

Also- the variable IGO spacing looks AWESOME! If this one HUC 10 is representative of elsewhere, I think this is the way to go!
![image](https://user-images.githubusercontent.com/73319684/226504156-ca0cdaa4-eb3b-4692-ae06-326b2a175cf0.png)

**Comment by joewheaton** [comment]
I agree with @lauren-herbine this is looking really, really promising on variable IGO spacing. There is obviously something weird going on at that one spot and I am not too worried about that.  The overall improvement on island thresholds and IGO spacing seems to help a ton with DGO quality!

**Comment by joewheaton** [comment]
@jtgilbert this is great. @jtgilbert, @shelbysawyer and @lauren-herbine should watch [this video](https://youtu.be/ya7q_uooA_A) I recorded for you and I flag up some issues in my feedback for each of you.  At a high level:
- There are a bunch of symbology and curation issues (mainly for @shelbysawyer but can be shared with @Riverscapes/riverscape-project-curators). 
- The change to the DGO/IGO window spacing making it variable (and 300 m in big valley bottoms) is a positive game changer for the quality of DGO geometry. Tons of things go away and look better with this more appropriate variable window size (FYI @philipbaileynar and @KellyMWhitehead).
- The change to island window size seems (from what I can tell) to have also helped (I don't know if I found any islands here). It makes me wonder whether we should have a separate layer for just VB Islands? Maybe not.
- I found one bug on Horseshoe Run that is due to a discrepancy between the channel area for Horseshoe Run and the bigger (correct) longer drainage line and it is resulting in no DGOs getting produced. It is flagged up consistently (I suspect) by a `CENTERLINE_COST_ERROR` in the levelpath_Debug.csv. 
- Symbology and project report curation can proceed independent of pace of VBET runs
- The parameterization of transform curves based on lines of evidence could be done NOW based on 0.9. @jtgilbert please begin this step.

Please make new issues and address changes in VBET 0.9.1.

**Comment by shelbysawyer** [comment]
**For the video:**
- @joewheaton The bug you mentioned in the video around 12:50 is a [known issue](https://github.com/Riverscapes/riverscapes-tools/issues/720). @jtgilbert Said this will be fixed when new runs are done using the V2 XML in new warehouse. Because this problem normally affects tributaries to the mainstem (where, I'm guessing, a good number of training points fall), it has the potential to skew our HAND evidence training values. @jtgilbert do you see us running the V2 XML for the RSContext for the 225 HUC10s so that it can be fixed before grabbing the HAND values, or do you see this as a non-issue?
- Agree with @lauren-herbine and @joewheaton that the updated island thresholding and updated variable spacing seems to have solved a lot of the problems we were seeing. Woohoo!
- I will create issues for the necessary curation, symbology, and report tasks mentioned in the video

**Other:**
- Please continue to click 'update resources' when exploring new projects. I pushed a new BL at the end of last week and will be making additional changes this week.
- I'm confused about the `seg_distance` field in DGOs that @joewheaton was talking about in the video. Can someone please explain what it is?

**Repeating my plea here** for explicit explanations (for documentation purposes) of what has been changed in 0.9.0:
- @jtgilbert What is the threshold for island/hole removal that we are looking at? Is it by area or cell size? What step are we applying this at?

**Comment by jtgilbert** [comment]
v0.9.0:
- changed stream size classification to be drainage area based rather than stream order.
- cleaned up the project database (not important for documentation).
- evidence weights are assigned in the project database.
- increased valley bottom raster hole filling threshold from 20 to 350 pixels.
- Variable IGO spacing (300m for large streams, 200m for medium, and 100m for small)

We do need to discuss what to do in terms of the channel area issue. The two options are:
- wait until the warehouse is launched and VBET xml updated to V2 before running all of the calibration watersheds
- run the calibration watersheds now on 0.9.0, knowing that there may be data points in channels that can't be used because of this issue.

@shelbysawyer seg distance is the distance along the centerline at which a given IGO is generated. This value, along with levelpath are present in both IGO and DGO attributes so that they can be associated. Sometimes the distance starts at the top of a segment and sometimes at the bottom, just because of the way the NHD lines were drawn.

**Comment by joewheaton** [comment]
> We do need to discuss what to do in terms of the channel area issue. The two options are:
> 
> * 1. wait until the warehouse is launched and VBET xml updated to V2 before running all of the calibration watersheds
> * 2. run the calibration watersheds now on 0.9.0, knowing that there may be data points in channels that can't be used because of this issue.
> 

I vote for option 2. 
> @shelbysawyer seg distance is the distance along the centerline at which a given IGO is generated. This value, along with levelpath are present in both IGO and DGO attributes so that they can be associated. Sometimes the distance starts at the top of a segment and sometimes at the bottom, just because of the way the NHD lines were drawn.

Is that something we need to fix or worry about for typology?  I know we worried about that in BRAT? If no, no big deal. If yes, can we use what we did in BRAT back at Channel Area project?

**Comment by jtgilbert** [comment]
@joewheaton for now I don't think it's a big deal, doesn't affect and functionality. We can revisit in the future if it becomes an issue or we just want to clean things up.

**Comment by shelbysawyer** [comment]
The next round of reviews (for versions >3) will be ticketed soon, once we have a batch of VBET projects in the new warehouse. Closing this.
