### ISSUE TITLE
URGENT - Update Riverscapes Context Metadata

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#732]
@joewheaton wants all metadata to be human readable. We are right on the cusp of running all our tools in the new warehouse and so we urgently need to surgically tweak our metadata. This issue is just for RSC. Issues for other tools to follow.

A few guidelines:

- Human readable keys should now contain spaces and correct capitalization (e.g. "Model Version" instead of `ModelVersion`)
- Where we know that a key is used by the system we should assign the type `hidden` so that it does not appear in the warehouse UI but is still present in the `project.rs.xml`
- When a metadata key needs to be both human readable AND reliable for the system to work (e.g. `HUC10` and `HUC`) then we will need to define different keys and set one to `hidden`.
- Note that metadata types are not always being set! URLs are not being formatted in the warehouse UI properly because the metadata type attribute is missing (witnessed on tauDEM projects).
- Where you anticipate a metadata key being reused by other riverscapes tools then consider abstracting the key to a constant somewhere and reusing it in each tool. This will provide consistently across our tools.
- Ensure that metadata types are being set for all entries! Ask @MattReimer if you don't know what this means.

# Existing Metadata

Key|Example Value|Action
---|---|---
ModelVersion|1.3.0|change key to Model Version
DateCreated|2023-04-03T21:50:14.081531| Keep but set type to `hidden`
HUC|0702000504| Keep but set type to `hidden`
HUC10|0702000504| Keep but set type to `hidden`
Runner|Cybercastor|Keep but set type of `hidden`
Watershed|Mud Creek| Changed key to `Watershed Name`
ProcTimes|140.71|Keep but change time to `hidden`
ProcessingTime|2:20 minutes|Change key to `Processing Time`

# New Metadata

Key|Example Value|Action
---|---|---
Projection Creation Date|23 Aug 2021|Human readable key and value
Watershed HUC Code|0702000504|Repeat of HUC

# Urgency

We are going to start running Riverscapes Context projects in new production warehouse on Tuesday.

# Screenshot

<img width="857" alt="Screenshot 2023-04-04 at 5 03 26 PM" src="https://user-images.githubusercontent.com/8645379/229948303-80e56117-e02f-4075-870c-531f0be160fa.png">

**Comment by jtgilbert** [comment]
fyi, I'm looking at the code now and the "ProcTimeS" metadata key was already set to hidden but is still showing up in the warehouse...

**Comment by MattReimer** [comment]
> - A short 1 sentence explanation of what MetaDaa is with a link to some developer resource page elaborating.

Cool. This is static. We can handle this.

> - A short explanation about how the MetaData for this project was generated (i.e. Automatic, Manual, Automatic with Manual Overides)

We won't actually know anything about how the metadata was generated since we don't track it. It could be 100% manual or 100% automatic. No way to know. Maybe I'm not understanding. 

> - The section of the Readable (non-hidden) keys

Yup, fine

> - A collapsible section of the Hidden Keys (the curious user, analyst or developer will want to see these)

It was always in the plan to have a button of some kind to toggle on and off the hidden metadata. I think it's all showing for now but it's not a hard UI task to toggle it. 

Couple of things:

- @jtgilbert let's talk. There are some nuances to this I want to make sure we're all on the same page
- We're talking about **_project metadata_** here. Not realization metadata, dataset metadata or dataset layer metadata.
- I have no specific opinions about how you format metadata. Whatever you choose should server the function you need it to. I do have a couple of thoughts to keep in mind.
    - The spaces shouldn't matter. We do the following with metadata keys when we index them for searching:
        - trim (i.e. remove whitespace on either side)
        - lowercase
        - remove all inner whitespace
        - replace any characters that do not fit the pattern `a-zA-Z0-9-_,.:` with `❌`

So this means if your metadata key is `   My MEtadATa  Key 😎🌈#      ` that gets indexed by the search engine as `mymetadatakey❌❌❌`. We apply the same transformation to search requests to balance out searchability with not having to be _exactly_ right.

> Should we lock down or make uneditable the hidden keys? Yesterday @philipbaileynar made a big deal about how important those are for the system and search. Do we really want people messing with those? Or are the permissions adequately restrictive on metadata editing for our production grade runs that this is a non-issue?

I don't think so. `hidden` doesn't imply anything other than "Something non-presentational." Our production-grade runs will belong to an organization in the system (TBD) and only people we trust can edit it. If people change hidden metadata that's fine but tools and scripts that depend on it might break.

**Comment by MattReimer** [comment]
@jtgilbert I'm going to tack some checklist items here leading up to our conversation

- [ ] Human readable metadata names for all project metadata
- [ ] `extRef=` for datasets needs to be set (we'll talk)
- [ ] metadata propogation with correct `ext=` attribute needs to be set (we'll talk)
- [ ] For now we should add a project metadata item for each input linking to where that lives in the API:

so for Taudem on the **project metadata**:

```xml
<MetaData>
	<Meta name="Model Version">1.1.0</Meta>
	<Meta name="Riverscapes Context" type="url">https://warehouse.riverscapes.net/p/eeb57eb6-fb33-471c-bd45-efd987bc8374</Meta>
	<Meta name="Channel Area" type="url">https://warehouse.riverscapes.net/p/eeb57eb6-fb33-471c-bd45-efd987bc8374</Meta>
</MetaData>

```

**Comment by jtgilbert** [comment]
@MattReimer should the Meta link to input projects have ext="project" or does it not need it.

**Comment by MattReimer** [comment]
No. No `ext=` needed on project metadata

**Comment by philipbaileynar** [comment]
@jtgilbert can you ensure that every project metadata includes a link to the tool website that generated it. e.g.

`https://tools.riverscapes.net/brat`

**Comment by jtgilbert** [comment]
I think all of this is addressed
