### ISSUE TITLE
RSContext: HUC6 and HUC4 are the same shape

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#752]
discovered as a result of #747 

The huc6 shape and the huc4 shape are the same. 

I feel like this has been raised before but I coul;dn't find an issue for it. 

This is a problem on huc 0502000403

https://warehouse.riverscapes.net/rv/0962270c-60f3-4128-a1f5-42dd0a0f4f05

but it is not a problem on 0708010504

https://warehouse.riverscapes.net/rv/18eec6b6-9bc8-4bcd-a310-f112c5844abb

It feels to me like something weird is treating `050200` and `0502` as the same thing. Maybe we're dropping zeros or something.

**Comment by jtgilbert** [comment]
I actually think in some regions the HUC4 and HUC6 are actually just the same. I noticed this too, but if you look in the raw .gdb the geometry for WBDHU4 and WBDHU6 are the same.

**Comment by MattReimer** [comment]
Oh, ok. Perfect. Let's close this then and hope next time it comes up I remember to search for this issue.

**Comment by philipbaileynar** [comment]
> I actually think in some regions the HUC4 and HUC6 are actually just the same. I noticed this too, but if you look in the raw .gdb the geometry for WBDHU4 and WBDHU6 are the same, and thats why they name the HUC6 with the two 0s on the end instead of 01 or something.

We have also noticed that the HUC2 polygon is just plain missing!

At some point we could upgrade and pull watershed boundary polygons from the [National Watershed Boundary Dataset](https://www.sciencebase.gov/catalog/item/51361e87e4b03b8ec4025c22). We wouldn't pull it from Science Base of course. We would download it into the National Project (given that these data are essentially static). Pulling HUC boundaries from  the NHD downloads appears to be rife with problems.

**Comment by joewheaton** [comment]
In #743 I see MAJOR issues with the how HUCs are displaying in WebRV with being clipped off, despite them showing up correctly in QGIS.  Also, this issue is NOT fixed in the runs we're reviewing. If you want to make a new issue that is okay. But the fix screwed up some things. The time is now to get this right. We don't keep kicking this can down the road.

**Comment by jtgilbert** [comment]
I just looked at the whole WBD and in many cases HUC4 and 6 are the same. Like I suspected, in those cases the final two digits of the 6 are 00, whereas they are 01, 02 etc. if the HUC6s are smaller than the HUC4. In the HUCs I've tested for the fix its correctly grabbing all of the basins from 2 to 12. Since this issue isn't related to symbology I'm closing.

**Comment by joewheaton** [comment]
Well that is interesting. Who knew. Just to confirm @jtgilbert, we are keeping both in these instances, even though they are duplicates of each other from a geometry stand point. I think that is the right way to proceed.

**Comment by jtgilbert** [comment]
Yes, I agree.
