### ISSUE TITLE
Channel Area and TauDEM Review - JW

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#768]
Channel Area

- [x] [501000301](https://warehouse.riverscapes.net/p/7f1320ca-e43d-4d73-9af2-c98bb9195a78/)
- [x] [701010102](https://warehouse.riverscapes.net/p/5bc5c41d-d72e-4e79-ac28-3c384a7d02c6/)
- [x] [1005000403](https://warehouse.riverscapes.net/p/16460bbb-540b-43b7-9c0b-76e346a3c621/)
- [x] [1601020203](https://warehouse.riverscapes.net/p/3cd4962b-9565-4a37-93bf-606d8ed7373e/)
- [x] [1706010302](https://warehouse.riverscapes.net/p/b613bd8a-d9b5-49e8-b480-4f3e5e9738e1/)

TauDEM

- [x] [501000301](https://warehouse.riverscapes.net/p/30963960-d0f8-463c-9301-44eaa1c33d59/)
- [x] [701010102](https://warehouse.riverscapes.net/p/00898015-c327-4d00-92f1-22f1621a5325/)
- [x] [1005000403](https://warehouse.riverscapes.net/p/57011dd4-6713-40ec-b110-864f91064361/)
- [x] [1601020203](https://warehouse.riverscapes.net/p/e6d6198c-3d7d-4033-823c-e4010b41f434/)
- [x] [1706010302](https://warehouse.riverscapes.net/p/7e4d9ddb-4103-42e0-9ab0-9d322ddda26a/)

**Comment by joewheaton** [comment]
Fairly uneventful @KellyMWhitehead, @MattReimer, @philipbaileynar, @jtgilbert, @lauren-herbine and @shelbysawyer. I did find some bugs. See video if bored: https://youtu.be/cMDtzcRvXaY of my process. 

## Channel Area Feedback
- [ ] In [1005000403](https://warehouse.riverscapes.net/p/16460bbb-540b-43b7-9c0b-76e346a3c621/) Channel Area the zoom extents were messed up in WebRV (see first part of video). 
- [ ] In [1706010302](https://warehouse.riverscapes.net/p/b613bd8a-d9b5-49e8-b480-4f3e5e9738e1/), the bankfull polygons were not rendering correctly (about 11 minutes in) 
- [ ] In [501000301](https://warehouse.riverscapes.net/p/7f1320ca-e43d-4d73-9af2-c98bb9195a78/) the Input Flow Areas are not showing up even though they are clearly there in intermediates (at 15 minutes). also observed in [701010102](https://warehouse.riverscapes.net/p/5bc5c41d-d72e-4e79-ac28-3c384a7d02c6/).



## Tau DEM
- [ ] Rasters are getting a "0" count for number of layers in Dataset Tab (doesn't seem right).
- [ ] Around 21:30 in [1005000403](https://warehouse.riverscapes.net/p/57011dd4-6713-40ec-b110-864f91064361/) I notice that HAND is not being calculated for the entire watershed. There are noDAta zones. Why? I haven't seen this before from TauDEM (it happens in VBET of course).  Actually, I think by 27:00 that this makes sense (@jtgilbert to confirm). Because TauDEM is d-inf flow direction based, it can't calculate it for cells outside the drainage. Thus, it highlights parts that the USGS HUC boundaries are incorrect.
- [ ] Around 23:00 in [1005000403](https://warehouse.riverscapes.net/p/57011dd4-6713-40ec-b110-864f91064361/) I notice that Channel Extent Raster has a weird data extent. It should have no-data for everything outside the analysis area (i.e. HUC 10) and false for everything inside.
- [ ] Around 23:45 in [1005000403](https://warehouse.riverscapes.net/p/57011dd4-6713-40ec-b110-864f91064361/) I notice that Flow Direction is NOT showing up in WebRV, but it exists and is fine in downloaded project and displays properly in QRV.


## For All
- [ ] For WebRV, it would be really nice if we could view the log file in another tab (i.e open as text file in our own text viewer or browser text viewer) instead of having to download.
- [ ] For WebRV, we should denote (maybe in tree) which feature classes we are displaying that are empty. 
- [ ] Map Zoom Warning dialog has broken images!

**Comment by joewheaton** [comment]
@philipbaileynar I don't have time to create issues. I will let you see which of above are issues and then you can close this ticket.

**Comment by MattReimer** [comment]
Issues created:

- https://github.com/Riverscapes/rs-web-monorepo/issues/357
- https://github.com/Riverscapes/rs-web-monorepo/issues/359
- https://github.com/Riverscapes/rs-web-monorepo/issues/360
- https://github.com/Riverscapes/riverscapes-tools/issues/774
