### ISSUE TITLE
wrong geojson being copied in docker cybercastor

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/riverscapes-tools#805]
I ran anthro fixes in cybercastor via dockerbox and the project_bounds.geojson that was copied into the project is incorrect. I've noticed this before and forgot to post. I think it may just be copying the same geojson into all projects.

**Comment by jtgilbert** [comment]
Here's the project https://warehouse.riverscapes.net/p/507916e1-b81d-4803-89d0-ccd65f6219e9/overview

**Comment by MattReimer** [comment]
There are a number of problems with this anthro project

1. This project is 1.5Gb uncomopressed since there seems to be a full copy of VBET project inside it.
2. The warehouse is correctly uploading the geojson that it finds. It is the geojson itself that is wrong. 

@jtgilbert we need to figure out where that `project_bounds.geojson` is coming from 

https://github.com/Riverscapes/riverscapes-tools/blob/master/packages/anthro/anthro/anthro_rs.py#L53

Seems like maybe the rscontext it is pulling from might be wrong?
