### ISSUE TITLE
Attributes on IGOs and DGOs for queries

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/riverscapes-tools#813]
@philipbaileynar if you recall, the pie charts of metrics I made for Alden from tools downstream of VBET weren't accurate because they were IGO counts, not area of riverscape. I need to update these tools to include an attribute for window area. 

In discussing this with @joewheaton, it also came up that we should probably be including some attributes on IGOs and DGOs that make them more useful for querying. For example, FCode should be ported over from NHD so that queries could limit to perennial streams, and Alden/other agency folks always want to be able to query by ownership.

I can start making some changes to VBET, and we should probably have a discussion about what should be included.
This also obviously is a big change to implement when we've already run VBET for everywhere and downstream tools for large areas, so maybe there is a way to use the api to just update the necessary layers and re-upload to the project...

**Comment by jtgilbert** [comment]
This will probably be clutch to simplify what Alden was just talking about re: getting inventory stats for focal lanscapes.

**Comment by philipbaileynar** [comment]
Some initial thoughts. I probably need to digest this more thoroughly...

Thinking about this as IGO/DGO attributes" introduces complexity that is quite limiting. You always have to have anticipated the attribute (e.g. FCode) *a priori* and brought it across, probably changing the database structure to add a new column.

Instead, what about thinking about the filtering attributes as metrics themselves. e.g. imagine a new metric called "Modal FCode". This metric is calculated like any other, i.e. using a little block of code that performs a geospatial operation and then stores the value in the same metric results table as any other metric. Then you can have other metrics that "post process" metric values into other metrics. 

@KellyMWhitehead does this in QRiS metrics. There are primary metrics that are calculated first (e.g. valley length and channel length) and secondary metrics that use primary metric values (channel sinuosity is a ratio of the prior metrics).

This approach let's you leverage metrics to calculate other metrics, which is fairly limitless. It also keeps the complexity low, because you don't need any new database structure to support this approach. Adding new attributes as metrics is a data change rather than a new structural change to add a new column. This is a much easier upgrade for existing projects.

**Comment by jtgilbert** [comment]
Looking at RME now, and the IGOs get the FCode value here.

**Comment by jtgilbert** [comment]
Added FCode, other relevant attributes added in RME
