### ISSUE TITLE
Riverscapes Context Revisions

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#833]
This ticket describes several improvements to the Riverscapes Tools model. This is the first of several tickets as we make a pass through all our tools and raise the bar now that we have learned some lessons a) running them 10,000 times, b) have more tools in the waterfall.

# NHD Flow Line Attributes
The NHD flow lines feature class that we use in downstream tools needs to have the following attributes. These attributes are needed directly on the feature class, not merely via a join to the VAA table.

- FCode
- LevelPath
- TotDASqKm
- Ownership
- Ecoregion (WHICH LEVEL?)
- US State

- [ ] #834 

# Internationalization

We now have versions of RSC in Canada and France. 

## Units

We want subsequent tools (e.g. Channel Area) to be able to consume RSC and determine the units dynamically:

- Option 1 - include units in Project XML
- Option 2 - include units in attribute field suffix

## FCode 

The same is true of `FCode`. Either we abstract the reach codes to the project XML, or we map the FCodes onto a riverscapes coding system that can be applied to other jurisdictions. Or both for safety to avoid having to re-run these in the future!

## Level Path

What does this mean internationally?

Should we rename this field to be `level_path` because: a) I despise the upper existing capital I at the end of `LevelPathI` and b) we use lower case everywhere else...

# Ownership

@Jdgilby very kindly tried to clean up the original land ownership national project layer. He inadvertently introduced lots of miniscule errors. He has since fixed the layer. Jordan has a copy. This new layer needs updating in the national project.

# Metadata audit

Review all project and layer metadata for completeness.

# Project Name

We were inconsistent across our tools on what we want the project titles to be. @joewheaton can you chime in on what we want the official name of riverscapes context US projects to be?

- Riverscapes Context for HUC 1809020302
- Riverscapes Context for Happy Valley

# Reports

- [ ] #848

**Comment by MattReimer** [comment]
It might be a good time to ask if the project type should appear in the project name. There are pros and cons but mostly we just want to be consistent/

### Pros for short names

- It frees up our design and interface choices so that we can choose when to show the project type and when to hide it Maybe we don't show the project type at all, maybe we show an icon, maybe we show the short name, maybe we show the long one. 
- It makes scanning easier. For example: if we are filtering a view to only Riverscapes context then the fact that every item's title starts with "Riverscapes context for blah blah blah" is redundant and when we shorten the string we may just get every line being:
    - "Riverscapes Cont..." 
    - "Riverscapes Cont..." 
    - "Riverscapes Cont..." 
    - "Riverscapes Cont..." 
    - This is really hard to make a choice

Seems like a good time to have the discussion...

**Comment by philipbaileynar** [comment]
See #847 for continuation of project name discussion.

**Comment by philipbaileynar** [comment]
@KellyMWhitehead reworked the hydro derivates GeoPackage produced by Riverscapes context. It was reviewed by Joe and we have tweaked it a few times. Closing this master issue. Leaving the reports and naming issues open.
