### ISSUE TITLE
BRAT segmentation

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/riverscapes-tools#945]
The latest runs of BRAT have used the NHD network that comes out of RSContext segmented by ownership, rather than how it was previously being segmented to a fixed length. As a result, segmentation lengths range from ~1m up to several kilometers, which is WAY to large of an area to be sampling the veg and making predictions on! We need to enforce a max length on the input network to BRAT.
FYI @joewheaton @philipbaileynar

**Comment by philipbaileynar** [comment]
Does this go away if we migrate BRAT to a riverscape model and use DGOs as the input instead of channel?

I was pleased when we decided to no longer segment into 300m channels within RSC. I'm disappointed that this means that BRAT now has to consider its own segmentation again (something I originally coded in 2019 but which we removed in lieu of the RSC segmentation).
